### PR TITLE
Switch the GEP-713 parable to refer to Chihiro.

### PR DESCRIPTION
**Pull request by kflynn**
Signed-off-by: Flynn <emissary@flynn.kodachi.com>

Clean up the parable in GEP-713 to use the name "Chihiro", as it
should since we long ago stopped using "Charlie". 🤦‍♂️ 

/kind gep

```release-note
NONE
```

### CODE REVIEW

**Comment by kflynn** [comment]
Cc @youngnick for completeness, since it's his GEP...

**Review by guicassolato — APPROVED** [review]
/lgtm

**Comment by kflynn** [comment]
Is there a reason this is still being held? is it just that we didn't unhold before KubeCon?

**Comment by robscott** [comment]
@kflynn good catch, hold is automatic for any changes that touch GEPs.

/lgtm
/hold cancel

**Comment by youngnick** [comment]
Thanks @kflynn, nice work.

**Pull request merged**
