### PR TITLE
Removing Gateway, GatewayClass, and HTTPRoute alpha types

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As I was working on #2919, it became clear that we no longer need to keep the alpha types around for Gateway, GatewayClass, and HTTPRoute. This API version was intentionally excluded from the v1 CRDs so there's no value in keeping the corresponding types around.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by howardjohn** [comment]
Idea LGTM. I tried to test it out in our code and it doesn't compile so I think some fixes are needed.. I am shocked the tests pass here.

```
$ go build ./...
# sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2
pkg/client/clientset/versioned/typed/apis/v1alpha2/gateway.go:41:48: undefined: v1alpha2.Gateway
pkg/client/clientset/versioned/typed/apis/v1alpha2/gateway.go:42:48: undefined: v1alpha2.Gateway
pkg/client/clientset/versioned/typed/apis/v1alpha2/gateway.go:43:54: undefined: v1alpha2.Gateway
pkg/client/clientset/versioned/typed/apis/v1alpha2/gateway.go:46:71: undefined: v1alpha2.Gateway
pkg/client/clientset/versioned/typed/apis/v1alpha2/gateway.go:47:60: undefined: v1alpha2.GatewayList
pkg/client/clientset/versioned/typed/apis/v1alpha2/gateway.go:49:139: undefined: v1alpha2.Gateway
pkg/client/clientset/versioned/typed/apis/v1alpha2/gateway.go:50:2: undefined: GatewayExpansion
pkg/client/clientset/versioned/typed/apis/v1alpha2/gatewayclass.go:41:53: undefined: v1alpha2.GatewayClass
pkg/client/clientset/versioned/typed/apis/v1alpha2/gatewayclass.go:42:53: undefined: v1alpha2.GatewayClass
pkg/client/clientset/versioned/typed/apis/v1alpha2/gatewayclass.go:43:59: undefined: v1alpha2.GatewayClass
pkg/client/clientset/versioned/typed/apis/v1alpha2/gatewayclass.go:43:59: too many errors
# sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2
pkg/client/listers/apis/v1alpha2/gateway.go:33:50: undefined: v1alpha2.Gateway
pkg/client/listers/apis/v1alpha2/gateway.go:36:2: undefined: GatewayListerExpansion
pkg/client/listers/apis/v1alpha2/gateway.go:67:50: undefined: v1alpha2.Gateway
pkg/client/listers/apis/v1alpha2/gateway.go:70:30: undefined: v1alpha2.Gateway
pkg/client/listers/apis/v1alpha2/gateway.go:71:2: undefined: GatewayNamespaceListerExpansion
pkg/client/listers/apis/v1alpha2/gatewayclass.go:33:50: undefined: v1alpha2.GatewayClass
pkg/client/listers/apis/v1alpha2/gatewayclass.go:36:30: undefined: v1alpha2.GatewayClass
pkg/client/listers/apis/v1alpha2/gatewayclass.go:37:2: undefined: GatewayClassListerExpansion
pkg/client/listers/apis/v1alpha2/httproute.go:33:50: undefined: v1alpha2.HTTPRoute
pkg/client/listers/apis/v1alpha2/httproute.go:67:50: undefined: v1alpha2.HTTPRoute
pkg/client/listers/apis/v1alpha2/httproute.go:67:50: too many errors
```

**Comment by shaneutt** [comment]
Looks good, but I would like to /hold for a bit to make sure we reduce surprise.

/cc @arkodg @sunjayBhatia @michaelbeaumont @kflynn @mlavacca @candita

**Comment by youngnick** [comment]
LGTM, but the required rebase will clear the command if I do it now.

**Comment by robscott** [comment]
Rebased and tests are passing, would appreciate another LGTM soon because other PRs will need to be rebased on top of this one when it gets in.

**Pull request merged**
