### PR TITLE
docs: Rename Services API to Gateway API in Getting Started

### PR DESCRIPTION
**Pull request by tomkerkhove**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Rename Services API to Gateway API in Getting Started

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tomkerkhove** [comment]
`ActionGroup.Name` & `Alerts.ActionGroup.ResourceId`

**Comment by robscott** [comment]
Thanks for catching this @tomkerkhove! This change LGTM, you'll just need to run `make docs` to get our presubmit tests to pass.

/ok-to-test

**Comment by tomkerkhove** [comment]
How can this cause a linting issue 😅

I'll clone the repo and take a look.

**Comment by tomkerkhove** [comment]
Ok I see now, the docs are generated into HTML

**Comment by robscott** [comment]
Thanks for fixing this! We're working on a way that won't require that extra generation step (https://github.com/kubernetes-sigs/gateway-api/pull/559) so this should be easier in the future.

/lgtm
/approve

**Comment by tomkerkhove** [comment]
No problem at all @robscott !

**Pull request merged**
