### PR TITLE
Update verify-all.sh:  added $t to explicitly tell which script had an issue during a failed test

### PR DESCRIPTION
**Pull request by TheInvincibleRalph**
What type of PR is this?
/fixed bugs

What this PR does / why we need it:

This PR explicitly tells which script has an issue in a failed test

Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/3282

### CODE REVIEW

**Comment by youngnick** [comment]
/ok-to-test

Thanks for this @TheInvincibleRalph, this is a good start!

I think the key thing we wanted to see here is a summary at the bottom of all the failed tests, listed by script filename - that way, when troubleshooting CI failures, we can scroll to the bottom and see what to look for.

**Comment by TheInvincibleRalph** [comment]
> /ok-to-test
> 
> Thanks for this @TheInvincibleRalph, this is a good start!
> 
> I think the key thing we wanted to see here is a summary at the bottom of all the failed tests, listed by script filename - that way, when troubleshooting CI failures, we can scroll to the bottom and see what to look for.

Oh, I think I get now. I'll modify the script for that now

**Comment by TheInvincibleRalph** [comment]
I have modified the script accordingly, @youngnick.

**Comment by TheInvincibleRalph** [comment]
```hack/verify-all.sh: line 84: FAILED_TESTS: unbound variable
make: *** [Makefile:113: verify] Error 1
+ EXIT_VALUE=2
+ set +o xtrace
```
@youngnick, does this meet your expectation?

**Comment by youngnick** [comment]
Uh, it will be great, but the "unbound variable error" is because the variable is defined as `FAILED_TEST`, but used as `FAILED_TESTS`, note the `S`.

Once that's in, I think this LGTM, but will need @robscott review as well.

**Comment by TheInvincibleRalph** [comment]
> Uh, it will be great, but the "unbound variable error" is because the variable is defined as `FAILED_TEST`, but used as `FAILED_TESTS`, note the `S`.
> 
> Once that's in, I think this LGTM, but will need @robscott review as well.

Ooops. I'll fix that now.

**Comment by robscott** [comment]
Thanks @TheInvincibleRalph!

/lgtm
/approve
/ok-to-test

**Pull request merged**
