### PR TITLE
unit test for listenersMatch in conformance utils

### PR DESCRIPTION
**Pull request by ibilalkayy**
**What type of PR is this?**

**What this PR does / why we need it**:

I have added the unit test for listenersMatch in conformance utils

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by ibilalkayy** [comment]
Hey @mikemorris What is "lgtm"?

**Comment by gyohuangxin** [comment]
@ibilalkayy "lgtm" means "looks good to merge" : ) Thanks for your PR. /lgtm

**Review by shaneutt — APPROVED** [review]
/lgtm

Thank you!

**Comment by ibilalkayy** [comment]
Thank you, @shaneutt!

**Pull request merged**
