### PR TITLE
Bump k8s.io deps to v0.26.0

### PR DESCRIPTION
**Pull request by lucacome**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates k8s.io dependencies to `v0.26.0`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by shaneutt — COMMENTED** [review]
Thanks, and welcome!

Looks right, I checked it out locally and tidy and verify are happy with it.

/ok-to-test

@lucacome out of curiosity is part of the impetus for this PR because you're using Gateway API as a library at NGinx?

**Comment by lucacome** [comment]
Hi @shaneutt yeah that's part of it, but just making an effort to keep all the k8s dependencies up to date in various projects 🙂

**Review by shaneutt — APPROVED** [review]

**Comment by lucacome** [comment]
Some of the k8s deps were updated in #1601

**Review by shaneutt — APPROVED** [review]
Checked it out locally again,

/lgtm

**Pull request merged**
