### PR TITLE
Add Additional API Testing for GEP-3171

### PR DESCRIPTION
**Pull request by jakebennert**
**What type of PR is this?**
/kind feature
/kind test

**What this PR does / why we need it**:
This PR adds additional tests for API changes made in #3283.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jakebennert** [comment]
@kflynn @robscott if you could take a look when you have a second 🙂

**Comment by robscott** [comment]
Thanks @jakebennert!

/ok-to-test
/approve

**Comment by robscott** [comment]
Thanks @jakebennert!

Will give @kflynn or others some time to take a look at this one, but if not, will plan on merging tomorrow.

**Review by kflynn — APPROVED** [review]
Ship it! 🙂

**Pull request merged**
