### PR TITLE
Adding Nick as a project maintainer

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
@youngnick has been a great contributor to Gateway API, excited to welcome him as a maintainer!

This also removes @danehans as a maintainer now that he'll no longer be able to contribute to the project in his new role. Really appreciate all his contributions to the project!

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

Note: Once this PR merges, I'll make a follow up PR to k/org to change the groups there as well.

/cc @bowei @danehans @jpeach @hbagdi @youngnick 
/hold

### CODE REVIEW

**Comment by bowei** [comment]
Thank you @danehans for all of your contributions!
Welcome Nick -- @youngnick -- long time contributor!



/lgtm

**Comment by youngnick** [comment]
Thanks everyone, happy to be becoming a maintainer!

**Pull request merged**
