### PR TITLE
[gwctl] Cleanup import packages in gwctl 

### LINKED ISSUE #2571: [gwctl] Cleanup import packages in gwctl
Multiple files in gwctl seem to importing `embed` package which may not be used anymore. One such example is in https://github.com/kubernetes-sigs/gateway-api/blob/68194976485b269e68214b5a40e5951815bbb80b/gwctl/cmd/main.go#L21

We most likely aren't using any sort of embeds anymore and can get rid of such imports.

While we're doing this, it could also be useful to separate out packages into sections ike:

```
import (
standard_lib

local_gwctl_repo_packages

other_repos
)
```

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by murthy95**
**What type of PR is this?**
/kind cleanup

-->
**What this PR does / why we need it**:
This PR removed unused imports and re structure imports in `gwctl`

**Which issue(s) this PR fixes**:
Fixes  #2571

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by gauravkghildiyal** [comment]
Thanks @murthy95 !

/ok-to-test
/lgtm

**Comment by robscott** [comment]
Thanks @murthy95!

/approve

**Comment by gauravkghildiyal** [comment]
@murthy95 I think you can get this submitted if you edit the PR description and include the release notes section:

````
```release-note
NONE
```
````

**Comment by murthy95** [comment]
@gauravkghildiyal done.

**Pull request merged**
