### PR TITLE
[release 1.1] Prepare release 1.1.1

### PR DESCRIPTION
**Pull request by mlavacca**
**What type of PR is this?**

**What this PR does / why we need it**:

Prepare README and bundle version for 1.1.1

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @mlavacca!

/lgtm
/approve

**Comment by arkodg** [comment]
any rough ETA on this release @mlavacca ? trying to time it with an Envoy Gateway patch release, would be great if this can be released by tomorrow, tia

**Comment by robscott** [comment]
@arkodg Yep, the plan is to release this tomorrow (31st).

**Pull request merged**
