### PR TITLE
Moving GEPs to separate directory for separate reviewers and approvers

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
This moves GEPs to a separate directory so that we can have separate reviewers and approvers for documentation and GEPs.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
Not sure if this will work as intended, holding to verify.

/hold

**Comment by robscott** [comment]
Looks like this worked: https://deploy-preview-1756--kubernetes-sigs-gateway-api.netlify.app/geps/overview/

/hold cancel

**Review by shaneutt — APPROVED** [review]
I like the directory being at the root of the repository anyhow! :+1: 

Looks good, but I will defer to @youngnick on the final actual LGTM for one more pair of :eyes:

**Comment by youngnick** [comment]
Yeah, this looks fine and I want to get it in so I can rebase my other PRs.

/lgtm

**Pull request merged**
