### PR TITLE
Documenting HTTP header modifiers

### PR DESCRIPTION
**Pull request by nvibert**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Adding documentation for HTTP Request and Response Headers modification.

```release-note
NONE
```

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]
Thank you for adding this!

**Comment by shaneutt** [comment]
Looked over the netlify preview, looks like it's rendering and reading right :thinking:

**Comment by nvibert** [comment]
> Looked over the netlify preview, looks like it's rendering and reading right 🤔

I just had the missing newline at the end of my YAML files - hopefully the last test should succeed this time around.

**Comment by youngnick** [comment]
/lgtm

Thanks @nvibert!

**Pull request merged**
