### PR TITLE
Add Contour conformance report for v0.8.1

### PR DESCRIPTION
**Pull request by sunjayBhatia**
**What type of PR is this?**

/area conformance

**What this PR does / why we need it**:

Adds conformance report for Contour v1.27.0 which supports Gateway API v0.8.1 and updates implementation summary.

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by skriss — APPROVED** [review]

**Comment by robscott** [comment]
Thanks @sunjayBhatia!

/approve

**Pull request merged**
