### PR TITLE
hack: fixup deepcopy-gen for CRDs

### LINKED ISSUE #955: Generated types not regenerating
**What happened**:

Looks like since (https://github.com/kubernetes-sigs/gateway-api/pull/945) the regeneration of the API types doesn't regenerate the `zz_generated.deepcopy.go` file.

**How to reproduce it (as minimally and precisely as possible)**:

`$ make generate`

### PR DESCRIPTION
**Pull request by stevesloka**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Puts back controller-gen logic to generate the zz_generated.deepcopy.go
file for v1alpha2 CRDs.

Signed-off-by: Steve Sloka <slokas@vmware.com>

**Which issue(s) this PR fixes**:
Fixes #955 

**Does this PR introduce a user-facing change?**:
```release-note
none
```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @stevesloka! Hopefully CLA can get fixed, otherwise LGTM.

/ok-to-test
/approve

**Comment by stevesloka** [comment]
@robscott I put a ticket into the helpdesk over the CLA. Honestly have no idea why it's not working. /shrug

**Pull request merged**
