### PR TITLE
Fix TLS guide with TLSRoute can be terminated

### PR DESCRIPTION
**Pull request by mike1808**
Previously guide stated that TLSRoutes cannot be terminated on the gateway, however, there is no requirement that the proxy to the backend hop has to be TLS when using TLSRoute. As it's about matching not the traffic protocol.

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Fix TLS guide with info that TLSRoutes can be used with TLS terminated at the gateway

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

No

### CODE REVIEW

**Comment by mike1808** [comment]
@k8s-ci-robot fixed my email in the commit as I already singed SLA

**Comment by hbagdi** [comment]
Yes, this seems correct.
TLSRoute can support Passthrough or Terminate, the downstream TLS behavior is configured in the listener and not the route.

/lgtm

Will leave approval to another pair of eyes.

**Comment by howardjohn** [comment]
/hold

I have some concerns, typing them up

**Comment by howardjohn** [comment]
I agree this change is implementable and solves a real problem. However, I do have some concerns.

Currently, there are essentially 3 protocols in play:
The downstream connection, the protocol we use for routing internally, and the upstream connection.


Often these are the same for all three - sometimes they are different. For example, we could have TLS, which terminated gives us HTTP for routing, and forward QUIC. Or we could just have HTTP for all three.

Currently, the Route type is determining the middle one (Ill call it "routing protocol"). This PR changes that - the middle protocol is TCP but we are controlling it with a TLSRoute.

This seems even more concerning if we think of HTTP. Lets say I want to Terminate HTTPS traffic, then I want a route to match on the X-My-Header AND the SNI value - so I am matching on TLS properties *and* HTTP properties. Is this something we want to support? If so, does that mean every route needs to contain the entirety of TLSRoute match (which is small today but can grow quite a bit)? If not, then is it ok that routing raw TLS traffic is more capable than HTTPS traffic?

**Comment by hbagdi** [comment]
> Currently, there are essentially 3 protocols in play:
The downstream connection, the protocol we use for routing internally, and the upstream connection.

> Often these are the same for all three - sometimes they are different. For example, we could have TLS, which terminated gives us HTTP for routing, and forward QUIC. Or we could just have HTTP for all three.

In this case, the Gateway terminating protocol and the matching protocol is the same = TLS.

>  This PR changes that - the middle protocol is TCP but we are controlling it with a TLSRoute.

My understanding was that TLSRoute matching in case of "Terminate" will be based on the TLS handshake that is terminating at the Gateway and not the TCP bytestream within it.

**Comment by howardjohn** [comment]
> My understanding was that TLSRoute matching in case of "Terminate" will be based on the TLS handshake that is terminating at the Gateway and not the TCP bytestream within it.

Right, my point is that changes the current semantics and introduces inconsistencies with HTTP(S)

**Comment by jpeach** [comment]
> > My understanding was that TLSRoute matching in case of "Terminate" will be based on the TLS handshake that is terminating at the Gateway and not the TCP bytestream within it.
> 
> Right, my point is that changes the current semantics and introduces inconsistencies with HTTP(S)

TLSRoute has never said anything about the protocol used to reach the backend service, it's all about matching on TLS-level metadata. The BackendPolicy and service AppProtocol is what ttriggers TLS to the backend service.

> Lets say I want to Terminate HTTPS traffic, then I want a route to match on the X-My-Header AND the SNI value - so I am matching on TLS properties and HTTP properties. 

This is supported since we recommend that SNI and HTTP authorities match (so the SNI match is implicit I suppose). I don't know of an in-principle objections to allowing TLS-layer match criteria in HTTP routes, but I haven't seen a proposal either. Maybe implementation experience with a custom match type would be interesting.

**Comment by robscott** [comment]
Relevant to https://github.com/kubernetes-sigs/gateway-api/issues/623

**Pull request closed without merging**
