### PR TITLE
Fix job problem of build docker image

### PR DESCRIPTION
**Pull request by wilsonwu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
I saw the job failed and try to fix.

**Which issue(s) this PR fixes**:
The main branch job failed.

### CODE REVIEW

**Review by youngnick — CHANGES_REQUESTED** [review]
Thanks for the PR, @wilsonwu.

However, I don't think that just removing the build tags is the right option. If you look at line 23 of the Dockerfile, you can see that those build tags are used in the `go build` command to set versions in the binary.

If the build tags are causing issues, I think that it's better to either figure out what's causing the issues, or remove all trace of them from the Dockerfile as well.

**Comment by wilsonwu** [comment]
> Thanks for the PR, @wilsonwu.
> 
> However, I don't think that just removing the build tags is the right option. If you look at line 23 of the Dockerfile, you can see that those build tags are used in the `go build` command to set versions in the binary.
> 
> If the build tags are causing issues, I think that it's better to either figure out what's causing the issues, or remove all trace of them from the Dockerfile as well.

I searched that, the `buildx` can support `--build-arg`, not sure the job base docker image `gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90` could support buildx or not?

**Comment by wilsonwu** [comment]
> > Thanks for the PR, @wilsonwu.
> > However, I don't think that just removing the build tags is the right option. If you look at line 23 of the Dockerfile, you can see that those build tags are used in the `go build` command to set versions in the binary.
> > If the build tags are causing issues, I think that it's better to either figure out what's causing the issues, or remove all trace of them from the Dockerfile as well.
> 
> I searched that, the `buildx` can support `--build-arg`, not sure the job base docker image `gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90` could support buildx or not?

I checked that the `gcb-docker-gcloud` image support `buildx`: https://github.com/kubernetes/test-infra/tree/master/images/gcb-docker-gcloud

**Review by wilsonwu — COMMENTED** [review]
Updated, how can I run the job to test it?

**Comment by shaneutt** [comment]
> Updated, how can I run the job to test it?

You should be able to use your own registry to run the script and test it locally, but if you're asking whether we can just run the job in CI as part of this PR to test it I don't think so, right @robscott ?

**Comment by wilsonwu** [comment]
> > Updated, how can I run the job to test it?
> 
> You should be able to use your own registry to run the script and test it locally, but if you're asking whether we can just run the job in CI as part of this PR to test it I don't think so, right @robscott ?

Got it, I will test it ASAP.

**Comment by wilsonwu** [comment]
> > > Updated, how can I run the job to test it?
> > 
> > 
> > You should be able to use your own registry to run the script and test it locally, but if you're asking whether we can just run the job in CI as part of this PR to test it I don't think so, right @robscott ?
> 
> Got it, I will test it ASAP.

Fixed and tested in local successful:
image

PTAL @shaneutt

**Review by shaneutt — APPROVED** [review]
/lgtm

Thanks for testing :+1:

**Pull request merged**
