### PR TITLE
Fix typo GatewaReason -> GatewayReason

### PR DESCRIPTION
**Pull request by panslava**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fixes typo GatewaReasonUnsupportedAddress -> GatewayReasonUnsupportedAddress

**Does this PR introduce a user-facing change?**:
```release-note
Fix typo: rename GatewaReasonUnsupportedAddress -> GatewayReasonUnsupportedAddress
```

I am not sure, how safe is that to do that

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]
Oh dear... yeah we'll need to update that. Thank you!

**Comment by panslava** [comment]
Thanks! I have some problems running full `make` locally, but `make generate` does not create new files, also CI failure seems like a flake? I will try to retest

/retest

**Comment by robscott** [comment]
Thanks @panslava! Everything looks good on your end - appears to be an error pulling golang:1.20 image, hoping it's resolved by tomorrow, but if not, we can look into this more closely.

**Pull request merged**
