### PR TITLE
feat: add envoy gateway conformance report

### PR DESCRIPTION
**Pull request by Xunzhuo**
**What type of PR is this?**

/area conformance

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
@Xunzhuo any updates on this?

**Comment by shaneutt** [comment]
Do you wanna bump this to `v0.8.0` instead of RC1?

**Comment by Xunzhuo** [comment]
Sure let me bump it tomorrow, it's late night here : )

**Comment by arkodg** [comment]
@Xunzhuo can you also link the badge next to the implementation info https://gateway-api.sigs.k8s.io/implementations/

**Comment by Xunzhuo** [comment]
@arkodg  done.

**Review by arkodg — APPROVED** [review]
thanks @Xunzhuo !
/approve

**Review by mlavacca — APPROVED** [review]
/approve

**Review by shaneutt — APPROVED** [review]
/lgtm

**Pull request merged**
