### PR TITLE
chore: format yaml file

### PR DESCRIPTION
**Pull request by zaunist**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Format yaml with  [yaml lint config](https://github.com/envoyproxy/gateway/blob/main/tools/linter/yamllint/.yamllint).

In addition to that, I would suggest adding a yamllinter to `gateway-api` project as well, but I noticed that the current project doesn't use github action as a ci, so I'm not sure if that's possible.

If it is possible, I would be happy to do it.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1600

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zaunist** [comment]
image

**Comment by shaneutt** [comment]
> In addition to that, I would suggest adding a yamllinter to gateway-api project as well, but I noticed that the current project
> doesn't use github action as a ci, so I'm not sure if that's possible.
> If it is possible, I would be happy to do it.

If it's possible to add it under the existing `make verify` directive than it will be [picked up by CI automatically](https://github.com/shaneutt/test-infra/blob/master/config/jobs/kubernetes-sigs/gateway-api/gateway-api-config.yaml#L22), otherwise it can just be a new Makefile directive we would just need to [update our CI configuration](https://github.com/shaneutt/test-infra/blob/master/config/jobs/kubernetes-sigs/gateway-api/gateway-api-config.yaml#L22).

**Comment by zaunist** [comment]
I have added lint configuration, and format all of the yaml, please take a look.

**Review by shaneutt — APPROVED** [review]
Looks good thank you for your contribution!

**Comment by shaneutt** [comment]
@zaunist we have a couple conflicts here that need to be resolved before we can proceed, let me know if I can help?

**Comment by zaunist** [comment]
> @zaunist we have a couple conflicts here that need to be resolved before we can proceed, let me know if I can help?



> @zaunist we have a couple conflicts here that need to be resolved before we can proceed, let me know if I can help?

I've synced the main branch,  and resolved the conflict.

**Pull request merged**
