### PR TITLE
Drop experimental banner for backend-protocol selection

### PR DESCRIPTION
**Pull request by dprotaso**
**What type of PR is this?**
/kind documentation
/gep

**What this PR does / why we need it**:
Docs changes for backend protocol selection for Gateway Release v1.2

**Which issue(s) this PR fixes**:

Part of https://github.com/kubernetes-sigs/gateway-api/issues/1911

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dprotaso** [comment]
/hold

This should be merged after 1.2 is cut - See: https://github.com/kubernetes-sigs/gateway-api/pull/3108#issuecomment-2130155616

**Comment by youngnick** [comment]
LGTM, thanks @dprotaso

/approve

**Review by shaneutt — APPROVED** [review]
/lgtm

**Pull request merged**
