### PR TITLE
chore: cleanup litespeed section on implementations page

### PR DESCRIPTION
**Pull request by rperper**
Added a section for the LiteSpeed Ingress Controller

**What type of PR is this?**

**What this PR does / why we need it**:

Announce LiteSpeed Ingress Controller Gateway API support.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

yes
```release-note
Announce LiteSpeed Ingress Controller Gateway API support.
```

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
/ok-to-test

**Comment by rperper** [comment]
I think I've done everything.  Is something missing?
Thanks!

**Review by shaneutt — APPROVED** [review]
/lgtm

**Comment by youngnick** [comment]
Hmm, looks like this did revert the recent changes to the GKE implementation as well. @robscott, you may need to redo, I think.

**Comment by shaneutt** [comment]
This is my bad. I originally saw this and mentioned it in [this comment](https://github.com/kubernetes-sigs/gateway-api/pull/1529#issuecomment-1310856363) but somehow it got away from me. I cherry-picked @robscott's original commit back on top to revert those changes and also maintain Rob's attribution and authorship: https://github.com/kubernetes-sigs/gateway-api/pull/1535

**Pull request merged**
