### PR TITLE
Conformance supported-features flag help string should include all va…

### PR DESCRIPTION
**Pull request by pegasas**
**What type of PR is this?**

/kind documentation
/area conformance

**What this PR does / why we need it**:

Add all support features for conformance for better reading & developing experience.

**Which issue(s) this PR fixes**:

https://github.com/kubernetes-sigs/gateway-api/issues/2324

**Does this PR introduce a user-facing change?**:

No.

### CODE REVIEW

**Comment by pegasas** [comment]
try to resolve https://github.com/kubernetes-sigs/gateway-api/issues/2324

**Review by sunjayBhatia — CHANGES_REQUESTED** [review]
we probably don't want to manually list out supported features since this list will have to be kept up to date and can easily become incorrect/incomplete

rather, lets try to use the `AllFeatures` set: https://github.com/kubernetes-sigs/gateway-api/blob/4ff1670a3b158c2baa83462ae246c1b876617bb5/conformance/utils/suite/features.go#L191

we can use the Set `UnsortedList` helper to get the contents, and then probably have to sort them so we ensure a stable order in the flag help string: https://pkg.go.dev/k8s.io/apimachinery/pkg/util/sets#Set.UnsortedList

**Comment by pegasas** [comment]
hi, @sunjayBhatia ,
I've make another version, 
it seems if we wants to use `suite` package on `flags`, then it will cause cycle import issue.
We may need to refactor the suite and put feature into an single subfolder.
Any suggestions on this?

**Pull request closed without merging**
