### PR TITLE
make embed.FS configurable

### PR DESCRIPTION
**Pull request by zirain**
**What type of PR is this?**

/kind test
/area conformance

**What this PR does / why we need it**:

make embed.FS configurable, let downstream project override manifests if needed.

xref: https://github.com/envoyproxy/gateway/pull/1239

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
The embedded filesystem used in the conformance test suite is now configurable,
and required as a `suite.Option` (if you use `suite.New()` however, the
default will be provided).
```

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM ! thanks
ptal @robscott @youngnick @shaneutt 
this is a no-op for existing projects leveraging the conformance tests and allows some downstream projects like Envoy Gateway to reuse the conformance test framework for implementation specific filter extension conformance tests.

**Comment by arkodg** [comment]
> Why not just `kubectl apply` (or equivilent) them before running the test?

that has been abstracted into the `suite` noun (and implemented in it) which we are trying to leverage (existing ways to apply, run clients, validate results).

**Review by shaneutt — APPROVED** [review]
Looks pretty simple, seems helpful, and I understand from @arkodg that this has been manually tested and is working well. It's also just generally low threat since it's conformance test suite only functionality. Looks good to me, I did update the release notes in the description with a little bit more explanation of effect on conformance test users as this will be landing in `v0.7.0`.

/lgtm

**Pull request merged**
