### PR TITLE
Add label filtering (-l) for `get namespaces`

### LINKED ISSUE #2913: [gwctl] Add label filtering (-l) for `get namespaces`
Refer https://gateway-api.sigs.k8s.io/geps/gep-2722/ for details

### PR DESCRIPTION
**Pull request by yeedove**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2913

**Does this PR introduce a user-facing change?**:

```release-note
Add label filtering (-l) for get namespaces
```

```
➜  gwctl get namespaces -l kubernetes.io/metadata.name=monitoring
NAME        STATUS  AGE
monitoring  Active  29d
```

### CODE REVIEW

**Comment by yeedove** [comment]
```
➜ gwctl get ns -l kubernetes.io/metadata.name=envoy-gateway-system
Unrecognized RESOURCE_TYPE
```
The command `gwctl get namespaces` is currently supported by gwctl, yet the shorthand `gwctl get ns` is not available,  Should I add `ns` as a shorthand to facilitate its use by users?

**Comment by gauravkghildiyal** [comment]
> ```
> ➜ gwctl get ns -l kubernetes.io/metadata.name=envoy-gateway-system
> Unrecognized RESOURCE_TYPE
> ```
> 
> The command `gwctl get namespaces` is currently supported by gwctl, yet the shorthand `gwctl get ns` is not available, should we add `ns` as a shorthand to facilitate its use by users?

Yes definitely, lets do it in the same PR.

**Comment by yeedove** [comment]
@gauravkghildiyal done, I'd like to continue working on `Add label filtering (-l) for describe commands`

**Comment by gauravkghildiyal** [comment]
Thanks @yeedove 

/ok-to-test
/lgtm
/approve

**Pull request merged**
