### PR TITLE
Additional Conformance Tests covering HTTPRoute and Gateway

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
As suggested by @hbagdi, this is a follow up PR to add the remaining conformance tests that were initially part of #969. 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
LGTM from me

**Comment by youngnick** [comment]
LGTM, once @bowei's comment is fixed up.

**Comment by youngnick** [comment]
/lgtm

Thanks for this Rob!

**Pull request merged**
