### PR TITLE
conformance/utils/kubernetes: Return more errors from DumpEchoLogs

### PR DESCRIPTION
**Pull request by sunjayBhatia**
**What type of PR is this?**
/kind cleanup
/kind test
/kind flake
/area conformance

**What this PR does / why we need it**:
Errors from streaming pod logs or reading logs were invisible to users running the suite since on error the loop through pods just continued.

This test has been flaky in CI so it would be good to know if that is caused by errors in the request fetching logs or otherwise.

**Which issue(s) this PR fixes**:
N/A

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
cc @LiorLieberman since you wrote the original test

**Comment by sunjayBhatia** [comment]
The test flake logs look like:

```
--- FAIL: TestGatewayConformance/HTTPRouteRequestMirror/0_request_to_'/mirror'_should_go_to_infra-backend-v1 (60.00s)
            httproute-request-mirror.go:69: Making GET request to http://172.18.255.200/mirror
            http.go:228: Request passed
            mirror.go:41: Searching for the mirrored request log
            mirror.go:42: Reading "gateway-conformance-infra/infra-backend-v2" logs
            mirror.go:41: Searching for the mirrored request log
            mirror.go:42: Reading "gateway-conformance-infra/infra-backend-v2" logs
...
            mirror.go:41: Searching for the mirrored request log
            mirror.go:42: Reading "gateway-conformance-infra/infra-backend-v2" logs
            mirror.go:37: 
                	Error Trace:	/home/runner/go/pkg/mod/sigs.k8s.io/gateway-api@v0.7.1/conformance/utils/http/mirror.go:37
                	            				/home/runner/go/pkg/mod/sigs.k8s.io/gateway-api@v0.7.1/conformance/tests/httproute-request-mirror.go:70
                	Error:      	Condition never satisfied
                	Test:       	TestGatewayConformance/HTTPRouteRequestMirror/0_request_to_'/mirror'_should_go_to_infra-backend-v1
                	Messages:   	Mirrored request log wasn't found
        apply.go:185: Deleting request-mirror HTTPRoute
```

**Comment by LiorLieberman** [comment]
Thanks @sunjayBhatia !

The continue was kinda by purpose because the requestMIrror filter is essentially mirror to a service - so we want to loop on all the pods to find the one which got the mirror request and I did not want to fail the test if we can find the mirror log in one pod but we have error reading from a different pod. 

I am wondering why the tests are failing - does the api have problems reading the log or it is just doesn't find them?

https://github.com/kubernetes-sigs/gateway-api/blob/ab03a594e7db13b8d2579929b204d8d10990fd2b/conformance/utils/http/mirror.go#L45

And right, seems like in the current code this should have been triggered only if the [list pods with that label](https://github.com/kubernetes-sigs/gateway-api/blob/ab03a594e7db13b8d2579929b204d8d10990fd2b/conformance/utils/kubernetes/logs.go#L39) returned error

**Comment by sunjayBhatia** [comment]
> Thanks @sunjayBhatia !
> 
> The continue was kinda by purpose because the requestMIrror filter is essentially mirror to a service - so we want to loop on all the pods to find the one which got the mirror request and I did not want to fail the test if we can find the mirror log in one pod but we have error reading from a different pod.
> 
> I am wondering why the tests are failing - does the api have problems reading the log or it is just doesn't find them?
> 
> https://github.com/kubernetes-sigs/gateway-api/blob/ab03a594e7db13b8d2579929b204d8d10990fd2b/conformance/utils/http/mirror.go#L45
> 
> And right, seems like in the current code this should have been triggered only if the [list pods with that label](https://github.com/kubernetes-sigs/gateway-api/blob/ab03a594e7db13b8d2579929b204d8d10990fd2b/conformance/utils/kubernetes/logs.go#L39) returned error

we have basically the same test and implementation of dumping the echoserver logs already in Contour's e2e testing that passes consistently ([here](https://github.com/projectcontour/contour/blob/main/test/e2e/gateway/request_mirror_test.go)) so still trying to figure out why the GW API one is flaking

this may be part of a solution, maybe instead we log errors in DumpEchoLogs and continue

**Comment by sunjayBhatia** [comment]
can't repro this flake any longer in CI or locally so closing this for now

**Pull request closed without merging**
