### PR TITLE
Change file name spec.html to _spec.html

### PR DESCRIPTION
**Pull request by nak3**
**What this PR does / why we need it**:

Currently URL for `gateway-api/spec` does not work although `gateway-api/spec/` works.

NG: https://kubernetes-sigs.github.io/gateway-api/spec
OK: https://kubernetes-sigs.github.io/gateway-api/spec/

(e.g. - [README](https://github.com/kubernetes-sigs/gateway-api/blob/fb69979683e254b83bd0ec99c405465b51d98bdc/README.md#references) uses the NG url.)

This is because `gateway-api/spec` shows [docs/spec.html](https://github.com/kubernetes-sigs/gateway-api/blob/master/docs/spec.html),
while `gateway-api/spec/` shows [docs/spec/index.html](https://github.com/kubernetes-sigs/gateway-api/blob/master/docs/spec/index.html).

To fix this issue, this patch changes file name `spec.html` to `_spec.html` in docs-src directory.

**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hbagdi** [comment]
/ok-to-test
/lgtm
/assign @robscott 
Rob is working on moving the website from Github pages to Netlify and this patch conflicts with his work. We can get this in first or after the migration is complete.

**Comment by robscott** [comment]
Hey @nak3, thanks for catching this! I think this will be resolved once #560 gets in - I added a comment explaining the change here: https://github.com/kubernetes-sigs/gateway-api/pull/560#discussion_r578603202. That renames the file to `genspec.html` which I'm not particularly tied to, but it should fix the root issue here. Once #559 gets in, this file along with all other generated docs files will be removed from git entirely. I think this is probably safe to close in favor of #560, but let me know if not.

**Comment by robscott** [comment]
With #560 merged in, I think this has been resolved. Feel free to reopen if not. Thanks again for catching this!

/close

**Comment by nak3** [comment]
sure, no problem at all! Thank you for the change.

**Pull request closed without merging**
