### PR TITLE
gep-1234: Formatting fixes around use cases for GAMMA initiative

### PR DESCRIPTION
**Pull request by david-yu**
**What type of PR is this?**

/kind gep

**What this PR does / why we need it**:

Mainly formatting to a GEP to make it easier to read

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

NONE 

```release-note

```

### CODE REVIEW

**Comment by david-yu** [comment]
Working through getting approval from EasyCLA at the moment. Thanks.

**Comment by david-yu** [comment]
Should be good to go now.

**Review by youngnick — COMMENTED** [review]
/lgtm

**Pull request merged**
