### PR TITLE
Doc: SecretObjectReference use "Secret" as Kind

### PR DESCRIPTION
**Pull request by kehao95**
According to the doc:
> A single CertificateRef to a Kubernetes Secret has “Core” support. Implementations MAY choose to support attaching multiple certificates to a Listener, but this behavior is implementation-specific.

and the line below
```
+kubebuilder:default=Secret
```
It looks like Secret should be the default implementation of the SecretObjectReference. And `HTTPRoute` or `Service` is certainly not a secret store.

**What type of PR is this?**

/kind documentation

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @kehao95! I think you're also going to need to run `make generate` locally and commit the changes to get our tests to pass.

/ok-to-test

**Comment by kehao95** [comment]
Hi @robscott, thank you for the guide. I've committed the generated changes. Should be good to merge now.

**Comment by robscott** [comment]
Thanks @kehao95!

/lgtm
/approve

**Pull request merged**
