### PR TITLE
Docs: route rule name

### LINKED ISSUE #3298: Documentation for the `name` field of route rules
Write documentation for the `name` field of route rules ([Experimental in v1.2](https://github.com/kubernetes-sigs/gateway-api/discussions/3103#discussioncomment-9505850)), which relates to the following:

- [GEP-995: Named route rules](https://gateway-api.sigs.k8s.io/geps/gep-995/)
- Implementation PR: https://github.com/kubernetes-sigs/gateway-api/pull/2985

/cc @robscott - you can assign this Issue to myself (I have no permission do that)

### PR DESCRIPTION
**Pull request by guicassolato**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

- Moves [GEP-995: Named route rules](https://gateway-api.sigs.k8s.io/geps/gep-995/) to Experimental
- Fixes the description of the format for route rule names in the GEP
- Documents the `name` field of route rule types in the _Reference > API Types_ section of the website

**Which issue(s) this PR fixes**:

Fixes #3298

**Does this PR introduce a user-facing change?**:

```release-note
Add documentation for route rule names
```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @guicassolato!

/ok-to-test
/approve
/hold for v1.2 release

**Comment by youngnick** [comment]
/lgtm

thanks @guicassolato!

**Pull request merged**
