### PR TITLE
Update WSO2 APK implementation status in docs

### PR DESCRIPTION
**Pull request by AmaliMatharaarachchi**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
The PR updates the WSO2 APK implementation status in the docs.

**Which issue(s) this PR fixes**:

None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by AmaliMatharaarachchi** [comment]
@robscott @keithmattix I would appreciate it if you could take a look. Thanks in advance.

**Comment by robscott** [comment]
Sorry we missed this @AmaliMatharaarachchi! This looks reasonable to me, do you happen to have any links showing that this already has GA support in WSO2?

**Comment by sanjeewa-malalgoda** [comment]
@robscott Please find some of the articles related to APK GA 1.0.0 Announcement.

GA 1.0.0 product documentation - https://apk.docs.wso2.com/en/latest/
Product page - https://wso2.com/api-platform-for-k8s
Announcement - https://wso2.com/about/news/wso2-introduces-wso2-api-platform-for-kubernetes/
Some news articles 
https://finance.yahoo.com/news/wso2-introduces-wso2-api-platform-130000393.htm

Thanks,
sanjeewa

**Comment by robscott** [comment]
Sounds good, thanks @AmaliMatharaarachchi! Out of curiosity, have you run any of our conformance tests yet?

/lgtm
/approve

**Pull request merged**
