### PR TITLE
Add kind/gep owner label for geps files

### PR DESCRIPTION
**Pull request by cnvergence**
**What type of PR is this?**

**What this PR does / why we need it**:
Add kind/gep label whenever PR contains gep files.

**Which issue(s) this PR fixes**:

Fixes 
- https://github.com/kubernetes-sigs/gateway-api/issues/2431

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]
Cool, so everything else is in place for this to work now? Thank you!

/ok-to-test
/approve
/lgtm

**Comment by cnvergence** [comment]
> Cool, so everything else is in place for this to work now? Thank you!
> 
> /ok-to-test /approve /lgtm

Still, automation for adding do-not-merge/hold is needed

**Comment by shaneutt** [comment]
> > Cool, so everything else is in place for this to work now? Thank you!
> > /ok-to-test /approve /lgtm
> 
> I saw that, by default, the owner-label plugin is enabled for this repo.
> 
> Still, automation for adding do-not-merge/hold is needed, not sure if adding it here would work as expected.

Should we just try it and find out?

**Comment by cnvergence** [comment]
Yeah, let's try

> > > Cool, so everything else is in place for this to work now? Thank you!
> > > /ok-to-test /approve /lgtm
> > 
> > 
> > I saw that, by default, the owner-label plugin is enabled for this repo.
> > Still, automation for adding do-not-merge/hold is needed, not sure if adding it here would work as expected.
> 
> Should we just try it and find out?

yeah, let's try it :)

**Review by shaneutt — APPROVED** [review]
/approve
/lgtm

**Comment by shaneutt** [comment]
let's try a test PR to change a GEP after this merges, and see if it handles it correctly :+1:

**Comment by cnvergence** [comment]
> let's try a test PR to change a GEP after this merges, and see if it handles it correctly 👍

seems like it handles it correctly, https://github.com/kubernetes-sigs/gateway-api/pull/2539

**Pull request merged**
