### PR TITLE
Removing scope fields from object references

### LINKED ISSUE #838: Scope in object references may be unnecessary
As a follow up from @howardjohn's v1alpha2 feedback in #790: 

>ParentRef.Scope is redundant. I know sig-apimachinery suggested it, but I disagree. Its inconsistent with Kubernetes - I don't run `kubectl get clusterrole --scope Cluster`, I run `kubectl get clusterrole` and the api-server knows it is cluster scoped. Why make users specify this boilerplate? It also gives users another way to create invalid config (ie Scope=Cluster Kind=Gateway); a great API makes it hard to create invalid configs.

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind cleanup
/kind api-change

**What this PR does / why we need it**:
Our object references use kind instead of resource which requires implementations to have a predefined kind->resource mapping. That means there can never be ambiguity within an implementation as far as whether a reference is to a cluster-scoped or namespace-scoped resource.

This also removes the ability for ParentRef to refer to cluster-scoped resources. Although we can add that in the future with a docs update. There do not appear to be any use cases for that today.

**Which issue(s) this PR fixes**:
Fixes #838 

**Does this PR introduce a user-facing change?**:
```release-note
* The `scope` field has been removed from all object references.
* ParentRefs can no longer refer to cluster-scoped resources.
```

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
:tada:

**Comment by robscott** [comment]
Discussed at community meeting yesterday as well, it seems like there's pretty broad consensus on this change.

/hold cancel

**Pull request merged**
