### PR TITLE
docs: note the pseudo headers should be allowed explicitly

### LINKED ISSUE #740: Clarify if psuedo-headers are supported within HTTP header matching
**What happened**:

Pseudo-headers can be used to specify matches against non-header properties of HTTP requests: https://github.com/kubernetes-sigs/gateway-api/pull/733#discussion_r676935043

**What you expected to happen**:

The documentation of the API clarify if pseudo-headers are supported or not.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

### PR DESCRIPTION
**Pull request by tokers**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Document the pseudo headers should be allowed by implementations.

**Which issue(s) this PR fixes**:

Fixes #740 

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by youngnick** [comment]
/ok-to-test

LGTM, but I'll let some others look before I issue the command. :)

**Comment by jpeach** [comment]
@tokers @youngnick I'm not that confident about which implementations support matching on pseudo-headers. Maybe a "SHOULD" would be better?

**Comment by tokers** [comment]
> @tokers @youngnick I'm not that confident about which implementations support matching on pseudo-headers. Maybe a "SHOULD" would be better?

If we use "SHOULD", then we also need to note the result if a solution doesn't implement it.

**Comment by hbagdi** [comment]
The current (in the mainline dev branch) guidance here is opposite: https://github.com/kubernetes-sigs/gateway-api/blob/5ac109cf2d1c98006e2672e4484e352ec320a412/apis/v1alpha2/httproute_types.go#L270-L281

The linked issue (#740) can probably be closed since we have the above text now.

I think we should refrain from adding this right now and come back post v1alpha2 if there is a demand.

**Comment by youngnick** [comment]
Sorry to lead you astray here @tokers.

**Comment by tokers** [comment]
> Sorry to lead you astray here @tokers.

Never mind. I also didn't notice the guidance pasted by @hbagdi . So it looks like now we can close this PR?

**Comment by hbagdi** [comment]
@tokers Seems like it.
I'll also close the linked issue.
/close

**Pull request closed without merging**
