### PR TITLE
Address comments made after PR was closed

### PR DESCRIPTION
**Pull request by keithmattix**
Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Addresses some wording clarifications and formatting changes for GEP 1324

**Which issue(s) this PR fixes**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by keithmattix** [comment]
cc @mikemorris

**Comment by robscott** [comment]
Thanks @keithmattix! Will leave final LGTM for @mikemorris 

/approve

**Review by shaneutt — APPROVED** [review]
/lgtm

**Review by mikemorris — APPROVED** [review]
/lgtm

**Pull request merged**
