### PR TITLE
improve SectionName examples and documentation for well-known resources

### PR DESCRIPTION
**Pull request by mikemorris**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Addresses concerns from https://github.com/kubernetes-sigs/gateway-api/pull/2813#discussion_r1554111330 that the behavior of `SectionName` for well-known resources is not sufficiently documented.

- [x] We'll want to add `* HTTPRoute: HTTPRouteRule name` to this as a followup if #2593 merges first @guicassolato 

**Which issue(s) this PR fixes**:
Refs #1031 , #2593

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @candita

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]
/ok-to-test
/approve
/cc @robscott

**Comment by robscott** [comment]
Thanks @mikemorris!

/lgtm

**Pull request merged**
