### PR TITLE
conformance: allow converence time for gateway status check

### PR DESCRIPTION
**Pull request by howardjohn**
Without this, other tests may be creating valid Routes that are
attached. This test can run and then immediately fail due to those
routes from other tests.

Instead, we should assert eventual consistency.

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
> Without this, other tests may be creating valid Routes that are attached. This test can run and then immediately fail due to those routes from other tests.

@howardjohn are you referring to a state where the same Gateway is used in consecutive tests, and the attachment state of a Route from a previous test case has not been cleaned up before the next test starts?

**Comment by howardjohn** [comment]
> > Without this, other tests may be creating valid Routes that are attached. This test can run and then immediately fail due to those routes from other tests.
> 
> @howardjohn are you referring to a state where the same Gateway is used in consecutive tests, and the attachment state of a Route from a previous test case has not been cleaned up before the next test starts?

Yes

**Review by skriss — APPROVED** [review]
LGTM, I believe we've run into this a couple times with Contour but I hadn't had a chance to dig into it yet.

**Comment by robscott** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
