### PR TITLE
Rework GRPCRoute API docs.

### PR DESCRIPTION
**Pull request by gnossen**
- Remove rationales
- Be more explicit about h2, h2c, prior knowledge, and ALPN.

**What type of PR is this?**

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @gnossen!

/ok-to-test

**Review by youngnick — COMMENTED** [review]
I like this wording, so I'll approve and let someone else LGTM.

/approve

**Comment by robscott** [comment]
Thanks @gnossen, this LGTM but needs a rebase now that https://github.com/kubernetes-sigs/gateway-api/pull/1576 merged.

/approve

**Comment by youngnick** [comment]
Updates #1016

**Pull request merged**
