### PR TITLE
docs: update resources included in different channels in installation guide page

### LINKED ISSUE #1846: Outdated guide on Resources in Different channels in "Installing Gateway API" docs
**What would you like to be added**:

In docs page https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api, The list of resources in standard channel and experimental channel are outdated, compared to the latest release v0.6.2. 

The standard (beta) channel should include: 
- `GatewayClass`
- `Gateway`
- `HTTPRoute`
- `ReferenceGrant` (missing)

The experimental (alpha) channel should include:
- `TCPRoute`
- `UDPRoute`
- `TLSRoute`
- `GRPCRoute` (missing)
- ~`ReferencePolicy`~ (should be removed) 

**Why this is needed**:

Keep docs in align with actual release.

### PR DESCRIPTION
**Pull request by randmonkey**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Keep the list of resources on gateway API installation guide page: https://gateway-api.sigs.k8s.io/guides/ to be synchronized to the actual status in latest release. 

**Which issue(s) this PR fixes**:

Fixes #1846

**Does this PR introduce a user-facing change?**:

```release-note
Documentation: updated outdated content on list of resources in installation guide page.
```

### CODE REVIEW

**Review by mlavacca — APPROVED** [review]
Thanks @randmonkey! 

/lgtm

**Review by shaneutt — COMMENTED** [review]
@randmonkey thanks for the PR! make sure to run `make generate` and commit any generated diff :+1:

**Comment by randmonkey** [comment]
> @randmonkey thanks for the PR! make sure to run `make generate` and commit any generated diff +1

@shaneutt merged the latest main branch and re-run `make generate`. Now The tests passed. @mlavacca Please look at the PR again?

**Review by mlavacca — COMMENTED** [review]
/lgtm

**Review by shaneutt — APPROVED** [review]
/lgtm

**Pull request merged**
