### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by LiorLieberman**
/cc @robscott

**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by robscott — APPROVED** [review]
Thanks @LiorLieberman!

**Review by shaneutt — COMMENTED** [review]
did this actually make it in to `v0.8.0` or was it intended for the imminent `v0.8.1`?

**Comment by robscott** [comment]
@shaneutt It made it into v0.8.0 (https://github.com/kubernetes-sigs/gateway-api/pull/2199), I just missed it in the changelog.

**Pull request merged**
