### PR TITLE
conformance: Update API version for timeout HTTPRoutes

### PR DESCRIPTION
**Pull request by sayboras**
**What type of PR is this?**

/kind test
/area conformance

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
/lgtm

**Comment by robscott** [comment]
Thanks @sayboras!

/approve

**Pull request merged**
