### PR TITLE
chore(docs): geps README.md created

### PR DESCRIPTION
**Pull request by mlavacca**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

A GEP README.md is created, to allow easier navigation and lookup of the needed GEPs.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @mlavacca! A couple questions:

1. Is this intended to be the main page for GEPs? It currently shows up in https://deploy-preview-2640--kubernetes-sigs-gateway-api.netlify.app/geps/, but that's not accessible via navigation.
2. Why aren't these grouped by stability level like the navigation?
3. I'm very concerned that this list will grow stale, similar to what already happens with or GEP navigation in `mkdocs.yml` where it's easy to forget to make a change. Is there any kind of automation you can add to mitigate that?

**Comment by tao12345666333** [comment]
+1 For this type of file, it is best to allow it to be automatically generated

**Comment by youngnick** [comment]
Yeah, I agree that a TOC like this should be autogenerated. Great idea though.

**Comment by mlavacca** [comment]
> Thanks @mlavacca! A few questions:
> 
> 1. Is this intended to be the main page for GEPs? It currently shows up in https://deploy-preview-2640--kubernetes-sigs-gateway-api.netlify.app/geps/, but that's not accessible via navigation.
> 2. Why aren't these grouped by stability level like the navigation?
> 3. I'm very concerned that this list will grow stale, similar to what already happens with or GEP navigation in `mkdocs.yml` where it's easy to forget to make a change. Is there any kind of automation you can add to mitigate that?

My idea was to give a ready-to-use table of content that can be used to quickly access GEPs, without going to documentation. I agree that we should add some machinery to automatically generate it. I'll add such machinery.

**Comment by robscott** [comment]
@mlavacca One note on any potential automation here, @youngnick is working on adding some additional metadata to GEPs, potentially in a more structured way. It's possible that would make it easier to generate a table of contents like this, you may want to wait for Nick's changes to get in before spending too much time on code to generate this.

**Comment by mlavacca** [comment]
> @mlavacca One note on any potential automation here, @youngnick is working on adding some additional metadata to GEPs, potentially in a more structured way. It's possible that would make it easier to generate a table of contents like this, you may want to wait for Nick's changes to get in before spending too much time on code to generate this.

Sounds good! Is there already any PR out about it?

**Comment by robscott** [comment]
@mlavacca do you want to rework this now that GEPs have metadata? (https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/gep-1016/metadata.yaml).

**Comment by mlavacca** [comment]
> @mlavacca do you want to rework this now that GEPs have metadata? (https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/gep-1016/metadata.yaml).

Yep, I'll revamp this PR soon. Thanks for the heads up @robscott

**Comment by youngnick** [comment]
Ping @mlavacca, not sure what you want to do with this PR for now?

**Comment by mlavacca** [comment]
I have no cycles to work on this at the moment, let's close it for now. In case we can re-open the PR in the future.

**Pull request closed without merging**
