### PR TITLE
bump up references to v0.2.0

### PR DESCRIPTION
**Pull request by hbagdi**
**What type of PR is this?**

/kind documentation
**What this PR does / why we need it**:
Bumps up the version used to install the CRDs to match the latest version.

**Which issue(s) this PR fixes**:

None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

Holding until release is out
/hold

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Does this mean we have two differernt versions of the same v1alpha1 version CRD?

**Comment by hbagdi** [comment]
> Does this mean we have two differernt versions of the same v1alpha1 version CRD?

Yes. We clarify this in our release info doc:
https://kubernetes-sigs.github.io/gateway-api/releases/

We are very open to alternative ways to do things post v0.2.0.

**Comment by robscott** [comment]
@hbagdi Tiny nit that PR name and commit message feel a bit off. Seems like you probably meant to say v0.2.0, otherwise LGTM.

**Comment by hbagdi** [comment]
> @hbagdi Tiny nit that PR name and commit message feel a bit off. Seems like you probably meant to say v0.2.0, otherwise LGTM.

My bad. Updated.

**Comment by robscott** [comment]
Thanks!

/lgtm

**Pull request merged**
