### PR TITLE
Adds HAProxy Kubernetes Ingress Controller to Gateway API Implementat…

### LINKED ISSUE #2779: Add HAProxy Kubernetes Ingress Controller to Gateway API Implementation page
**What would you like to be added**:

On https://gateway-api.sigs.k8s.io/implementations/, I'd like to add the following implementation:

> ### HAProxy Kubernetes Ingress Controller
>
> HAProxy Kubernetes Ingress Controller is an open-source project maintained by HAProxy Technologies that provides fast and efficient traffic management, routing, and observability for Kubernetes. It has built-in support for the Gateway API since version 1.10. The same deployment of the ingress controller will allow you to use both the Ingress API and Gateway API. See the [documentation](https://www.haproxy.com/documentation/kubernetes-ingress/gateway-api/enable-gateway-api/) for more details. In the [GitHub repository](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/gateway-api.md), you will also find additional information about supported API resources.

**Why this is needed**:

To provide Gateway API implementation information for those looking in the K8s docs.

Relevant source file: https://github.com/kubernetes-sigs/gateway-api/blob/main/site-src/implementations.md

### PR DESCRIPTION
**Pull request by NickMRamirez**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2779 

**Does this PR introduce a user-facing change?**:

-->
```release-note
* DOCUMENTATION: Added HAProxy Kubernetes Ingress Controller to Gateway API Implementations page.
```

### CODE REVIEW

**Comment by NickMRamirez** [comment]
@robscott To your question "have you tried running conformance tests with your implementation yet?" I am asking our developers about that.

**Comment by NickMRamirez** [comment]
@robscott , 

> I'd recommend noting that in the description of your implementation here.

My concern here is that the implementation and Gateway API version it's based on are subject to change. My feeling is that it's better for the user to go to the docs for the project and see what's new there. What do you think? 

I'll pass along the idea to test against v1.0 to the developers.

You are correct about the two HAProxy implementations. Naming is tricky. It's certainly something we've contended with, since users do get confused by the two projects. But after a lot of discussion, we haven't come up with a solution, unfortunately.

**Comment by robscott** [comment]
>My concern here is that the implementation and Gateway API version it's based on are subject to change. My feeling is that it's better for the user to go to the docs for the project and see what's new there. What do you think?

I think the vast majority of implementations in this list support HTTPRoute and do not support TCPRoute, so unless you're working to change that sometime soon, it could be useful to call out the difference and save prospective users some time. Certainly not a requirement though. 

This will all eventually be resolved when @xtineskim completes https://github.com/kubernetes-sigs/gateway-api/issues/2550, which should show the features that all implementations support, as long as they've submitted a conformance report - see https://gateway-api.sigs.k8s.io/geps/gep-1709/ for more. As you note though, TCP is definitely a gap in our conformance coverage right now, so until we resolve that, mentioning support directly is probably the best path.

With all that said, it's great to see another implementation here. Feel free to submit follow up PRs if you'd like to tweak anything, but I think this is good to go as is.

/lgtm
/approve

**Comment by shaneutt** [comment]
We don't need to block this PR for it, but at some point we should go back to our discussions about orgs with multiple Gateway API projects, as there may be some better ways we can provide display and organization for users who find their way into the page.

**Comment by NickMRamirez** [comment]
Thanks all!

**Pull request merged**
