### PR TITLE
remove unnecessary S in ProtocolType validation

### PR DESCRIPTION
**Pull request by spacewander**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

remove unnecessary S in ProtocolType validation

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spacewander** [comment]
@youngnick 
Would you take a look at this? Thanks!

**Comment by robscott** [comment]
Thanks for catching this one @spacewander!

/approve

**Comment by gauravkghildiyal** [comment]
Thanks!

/lgtm

**Pull request merged**
