### PR TITLE
Adding changelog for v0.5.0-rc2

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This will trigger one final release candidate before the v0.5.0 release.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/hold for consensus

### CODE REVIEW

**Comment by youngnick** [comment]
A second RC is a good idea, while I finish cleaning up my two outstanding things, thanks @robscott!. Sorry to be slow.

/lgtm

**Review by shaneutt — APPROVED** [review]
/lgtm

**Pull request merged**
