### PR TITLE
Reorganizes Validation Files

### PR DESCRIPTION
**Pull request by danehans**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Organizes validation into separate files based on the resource type.

**Does this PR introduce a user-facing change?**:

```NONE```

### CODE REVIEW

**Comment by hbagdi** [comment]
@danehans I think https://github.com/kubernetes-sigs/gateway-api/pull/668 solves part of this. Please rebase and re-organize if needed.

**Comment by robscott** [comment]
@danehans now that #668 is in, this PR needs to be rebased. It looks like #668 may have already done most of this reorganizing, but if there's anything it missed I'd love to get it in.

**Comment by robscott** [comment]
@danehans not sure if there's anything left in this PR with #668 merged in, but if so, this needs to be rebased.

**Comment by danehans** [comment]
Closing this issue since https://github.com/kubernetes-sigs/gateway-api/pull/668 took care of the reorganization.

**Pull request closed without merging**
