### PR TITLE
Update Contour implementation summary and conformance report

### PR DESCRIPTION
**Pull request by sunjayBhatia**
**What type of PR is this?**

/kind documentation
/area conformance

**What this PR does / why we need it**:

Updates contour implementation blurb on the site and add updated conformance report for contour v1.26.0

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Left out swapping the `latest` symlink to v0.8.0 but can include if desired

**Review by skriss — APPROVED** [review]
💯

**Comment by robscott** [comment]
Very impressive @sunjayBhatia and @skriss!

/lgtm
/approve

**Pull request merged**
