### PR TITLE
docs: Transition to crd-ref-docs

### PR DESCRIPTION
**Pull request by gcs278**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Update to use crd-ref-docs which is actively maintained and includes improvements over gen-crd-api-reference-docs.

**Which issue(s) this PR fixes**:
#3016

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

WIP: Still ironing out the details to keep get the https://gateway-api.sigs.k8s.io/reference/spec page looking similar to what we have now.

### CODE REVIEW

**Comment by gcs278** [comment]
Update: Unfortunately it's not a just-plug-it-in thing. I have a couple of things to figure out:

1. Sorting of Packages / API Versions (i.e. what https://github.com/kubernetes-sigs/gateway-api/pull/1345 tried to solve, may not be easily solvable/maintainable)
2. Sorting of types within a package. The current implementation puts "Kinds" (GRPCRoute, Gateway...) before individual types. It makes sense to do that. Not totally sure how that happens, but it's clear crd-ref-docs sorts alphabetically. For example, for v1 [currently](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1) GRPCRoute comes first, followed by Gateway, but in our this PR it [starts](https://deploy-preview-3204--kubernetes-sigs-gateway-api.netlify.app/reference/spec/#gatewaynetworkingk8siov1) with `AddressType`
3. Since it's running through `mkdocs` we get a Table of Contents. That's good I suppose?
4. Inline tables: For example, GRPCRoute's [spec](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GRPCRoute) is an inline table, but this PR doesn't create that inline table. I think there is a way to do this, just need to do some research.
5. Formatting. Headers are different sizes, tables have different columns, and information is display in a different formats.

Side note: The type in current docs  [GRPCRouteFilter](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GRPCRouteFilter) is displaying `gateway:experimental:validation:Enum=ResponseHeaderModifier;RequestHeaderModifier;RequestMirror;ExtensionRef` in the description field.

I'll need to get back to some of my regular scheduled programming, but I'm going leave this here for when I get some free time to fiddle with this implementation. I won't offended if someone finds this PR and wants to pick it up from here.

**Comment by robscott** [comment]
Thanks for the work on this @gcs278! Unfortunate that it's not just a drop-in replacement, but hopefully it's possible to get past some of these limitations at some point. It's interesting to see the [way Elastic uses this package](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-api-agent-k8s-elastic-co-v1alpha1.html) with different pages for each API group. I'm not sure if that would help us out here, but it might make things a bit easier to understand. Ideally there would be an easy way to exclude types from pages and/or highlight only root objects.

I think Envoy Gateway also uses this for their reference docs, maybe @arkodg or someone else working on that project would have some tips here?

**Comment by gcs278** [comment]
> It's interesting to see the [way Elastic uses this package](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-api-agent-k8s-elastic-co-v1alpha1.html) with different pages for each API group. I'm not sure if that would help us out here, but it might make things a bit easier to understand.

I like that formatting. It feels more organized to not have every API version on a single page (I use ctrl-f a lot and that can be confusing looking for a specific field).

**Comment by arkodg** [comment]
ccing @zirain here who may have asnwers to some of the questions @gcs278 had

**Comment by gcs278** [comment]
Note: https://github.com/elastic/crd-ref-docs/pull/86 will be pretty important, as crd-ref-docs always returns exit code 0, even when it fails generations.

I also opened https://github.com/elastic/crd-ref-docs/pull/85 as the markdown template examples had incorrect format.

**Comment by gcs278** [comment]
Unfortunately I don't have the bandwidth to keep this going, and I'd like to focus on other Gateway API items, but I am willing to help support anyone that wants to pick this back up and work on it.
/close

**Pull request closed without merging**
