### PR TITLE
Fix typo `It's is`

### PR DESCRIPTION
**Pull request by astraw99**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fix typo `It's is` to `It is`, to better the doc.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by astraw99** [comment]
> /approved

@jpeach The bot did not merge, the command should be "/approve"?

**Comment by robscott** [comment]
Thanks!

/approve

**Pull request merged**
