### PR TITLE
Edit Nginx timeouts diagram to match Envoy's in gep-1742.md

### PR DESCRIPTION
**Pull request by spacewander**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Adjust the Nginx timeout diagram according to the Envoy's. For example, adding missing client side request timeout, moving connect timeout.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @spacewander! Will defer to @pleshakov and/or @brianehlert to confirm. Here's the deploy preview for reference: https://deploy-preview-2117--kubernetes-sigs-gateway-api.netlify.app/geps/gep-1742/#nginx-timeouts

/ok-to-test

**Review by pleshakov — APPROVED** [review]
> Thanks @spacewander! Will defer to @pleshakov and/or @brianehlert to confirm. Here's the deploy preview for reference: https://deploy-preview-2117--kubernetes-sigs-gateway-api.netlify.app/geps/gep-1742/#nginx-timeouts

the edits look good to me 👍 

I noticed a few more missing timeouts:
- [client_body_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout) between client and NGINX
- [send_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#send_timeout) between client and NGINX
- [keepalive_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout) between NGINX and client

happy to add those things in a separate PR.

**Comment by spacewander** [comment]
> > Thanks @spacewander! Will defer to @pleshakov and/or @brianehlert to confirm. Here's the deploy preview for reference: [deploy-preview-2117--kubernetes-sigs-gateway-api.netlify.app/geps/gep-1742/#nginx-timeouts](https://deploy-preview-2117--kubernetes-sigs-gateway-api.netlify.app/geps/gep-1742/#nginx-timeouts)
> 
> the edits look good to me 👍
> 
> I noticed a few more missing timeouts:
> 
>     * [client_body_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout) between client and NGINX
> 
>     * [send_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#send_timeout) between client and NGINX
> 
>     * [keepalive_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout) between NGINX and client
> 
> 
> happy to add those things in a separate PR.

@pleshakov 
Thanks for your suggestion!

**Comment by robscott** [comment]
Thanks @spacewander and @pleshakov!

/lgtm
/approve

**Pull request merged**
