### PR TITLE
conformance: refactor listenersMatch and parentsMatch helpers

### LINKED ISSUE #1142: conformance: refactor listenersMatch and parentsMatch helpers into a single generic function
**What would you like to be added**:

Refactor `listenersMatch` (added in #1081) and `parentsMatch` to be a single generic function, or at least wrappers around a single generic implementation of the core logic.

**Why this is needed**:

The core logic of these two functions is quite similar (searching for all expected items in a slice of actual items, including the unimplemented need to support an arbitrary ordering), and it would be better to have this logic implemented once than risk two similar implementations diverging.

### PR DESCRIPTION
**Pull request by FlorentFlament**
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1142

Conformance helpers has been refactored to enable future improvements,
like matching arbitrarily ordered elements of lists for listenersMatch
and parentsMatch.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Deals with an opened issue #1142.  This will enable further improvements for compliance testing.

**Which issue(s) this PR fixes**:
Fixes #1142 

**Does this PR introduce a user-facing change?**:
None
```release-note

```

### CODE REVIEW

**Comment by youngnick** [comment]
Hi @FlorentFlament, could you rebase? I had a really quick look and I think this is pretty close, although we may need to put a generics policy into CONTRIBUTING. I'll put that on the agenda for next week's meeting.

**Comment by FlorentFlament** [comment]
Hi Nick,
Sure, I can rebase this PR. Don't hesitate to tell me if this requires further rework, or whether this is still relevant.
Regards

**Comment by mikemorris** [comment]
Refs https://github.com/kubernetes-sigs/gateway-api/issues/1388 re adding an explicit generics policy.

**Comment by shaneutt** [comment]
@FlorentFlament it's been a long time since we've heard back from you on this, are you still available to finish this up?

If not that's OK, and we still appreciate your time but if you need to drop it, or if we don't hear back from you we'll open it up for someone else to finish it, just let us know.

**Comment by shaneutt** [comment]
This is quite old and we haven't gotten a response back from the author so we're going to close this for now. #1142 has been made available again for someone else to take on if they'd like to continue this work (or if the author returns we can re-open this and continue).

**Pull request closed without merging**
