### PR TITLE
Improve GRPCRoute Go Structs

### PR DESCRIPTION
**Pull request by gnossen**
/kind bug

Fixes some uniformity issues in the Go API for `GRPCRoute`, bringing it into line with `HTTPRoute`. This affects only the Go API, not the CRD.

**Does this PR introduce a user-facing change?**:

```release-note
Add concrete instances of GRPCRouteFilterType and embed GRPCRouteBackendRef.BackendRefs.
```

### CODE REVIEW

**Comment by gnossen** [comment]
CC @howardjohn

**Review by howardjohn — APPROVED** [review]
:+1:

**Review by shaneutt — APPROVED** [review]
/lgtm

**Comment by shaneutt** [comment]
generators need to be run

**Comment by robscott** [comment]
Thanks @gnossen!

/lgtm

**Comment by youngnick** [comment]
Updates #1016

**Pull request merged**
