### PR TITLE
Correct util/translator function documentation

### PR DESCRIPTION
**Pull request by MichaelVL**
**What type of PR is this?**

**What this PR does / why we need it**:
This PR corrects documentation for all the string to type xx' translater functions.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]
/lgtm

**Comment by MichaelVL** [comment]
Sure @gyohuangxin - I have added similar changes for `v1alpha2`

**Review by gyohuangxin — APPROVED** [review]
Thanks, LGTM

**Review by shaneutt — APPROVED** [review]
Thanks for catching this! :vulcan_salute: 

/lgtm

**Review by keithmattix — APPROVED** [review]

**Pull request merged**
