### PR TITLE
Add the correct IP to the EndpointSlice

### PR DESCRIPTION
**Pull request by dprotaso**
**What type of PR is this?**

/kind test
/kind bug
/area conformance

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2986

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dprotaso** [comment]
/assign @howardjohn 

I've verified this on Istio+GKE with dual stack - will confirm this works with Istio+Kind where John reported it first

/hold for verification

**Review by howardjohn — APPROVED** [review]

**Comment by dprotaso** [comment]
/hold cancel

For folks wanting to verify I used this blog post to create a dual stack GKE cluster 
https://medium.com/@esteban.bouza/gke-ipv6-467147c0c57f

**Comment by robscott** [comment]
Thanks @dprotaso!

/approve

**Pull request merged**
