### PR TITLE
add option to specify http roundtripper while running conformance tests

### LINKED ISSUE #1496: Conformance RoundTripper should allow for custom http.RoundTripper implementation
**What would you like to be added**:

Allow for optionally constructing the `roundtripper.DefaultRoundTripper` with a custom `http.RoundTripper`.

**Why this is needed**:

Users may need to run conformance tests through a SSH tunnel or Proxy where a custom `http.RoundTripper` is required to connect to the load balancer.

https://github.com/kubernetes-sigs/gateway-api/blob/0adb8a8bd14672db6ea16ab6191a828295fe8d04/conformance/utils/roundtripper/roundtripper.go#L70

### PR DESCRIPTION
**Pull request by akash-gautam**
**What type of PR is this?**
/area conformance

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1496 

**Does this PR introduce a user-facing change?**:
No
```release-note
NONE

```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @akash-gautam!

cc @briantkennedy

**Comment by briantkennedy** [comment]
It looks like the original Issue (#1496) is no longer feasible due to the need for [setting a trusted CA certificate](https://github.com/kubernetes-sigs/gateway-api/blob/78ab14e85845c249cf5b014b2f4e769c67b128db/conformance/utils/roundtripper/roundtripper.go#L128).  I think we could still benefit from being able to configure the `Dial` member on the `http.Transport` resource ([reference](https://pkg.go.dev/net/http#Transport)).

**Comment by akash-gautam** [comment]
@briantkennedy So should we close this PR and the related issues and open a new issue for configuring Dial member?

**Comment by briantkennedy** [comment]
Yes @akash-gautam, that would be a simpler way to resolve.  Thanks!

**Pull request closed without merging**
