### PR TITLE
Refactor gwctl: restructure codebase, add new commands, and enable extensions

### PR DESCRIPTION
**Pull request by gauravkghildiyal**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Apologies for the large size of this PR, but it represents a significant step forward in making gwctl more usable and extensible. **The updated [README.md](https://github.com/gauravkghildiyal/gateway-api/blob/gwctl-revamp/gwctl/README.md) provides a comprehensive overview of all the latest capabilities.**

- Introduce new command structure and new commands (Highlights: [analyze](https://github.com/gauravkghildiyal/gateway-api/blob/gwctl-revamp/gwctl/README.md#resource-analysis-with-gwctl-analyze), [apply](https://github.com/gauravkghildiyal/gateway-api/blob/gwctl-revamp/gwctl/README.md#example-loading-resources), [delete](https://github.com/gauravkghildiyal/gateway-api/blob/gwctl-revamp/gwctl/README.md#deleting-resources))
- Implement [extensions and validation](https://github.com/gauravkghildiyal/gateway-api/tree/gwctl-revamp/gwctl/pkg/extension) (think of this like k8s webhooks that operate on a provided input and return validations / modifications)
- Improve topology [visualization](https://github.com/gauravkghildiyal/gateway-api/blob/gwctl-revamp/gwctl/README.md#visualizing-relationships-with-dot-graphs-using-gwctl-get--o-graph) and graph generation.
- Enabled CRUD operations for non-Gateway resources.
- Better error handling and reporting details to the user

Next steps:

- Provide a contributions guide to facilitate adding more validations and extensions.
- Expand unit and integration test coverage. I have added some basic framework for integration tests.

**Does this PR introduce a user-facing change?**:

```release-note
Add features analyze, apply, delete and graphing to gwctl. 
```

/area gwctl

### CODE REVIEW

**Review by mlavacca — COMMENTED** [review]
Thanks for all the work on this, @gauravkghildiyal! 

This PR looks massive and I honestly find the review of such a big piece of code very hard. Since in the PR description you outlined what the PR is about (this is great description) I wonder if it is possible to split this PR into multiple smaller PRs, focused on a specific area of improvement/refactoring. Do you think it's feasible? It'd help a lot the review :)

**Comment by gauravkghildiyal** [comment]
> Thanks for all the work on this, @gauravkghildiyal!
> 
> This PR looks massive and I honestly find the review of such a big piece of code very hard. Since in the PR description you outlined what the PR is about (this is great description) I wonder if it is possible to split this PR into multiple smaller PRs, focused on a specific area of improvement/refactoring. Do you think it's feasible? It'd help a lot the review :)

Thanks for taking the time to help with this @mlavacca. I totally feel the pain of reviewing a PR like this. I've started with splitting this into individual commits, ordered in a manner to make things easier to review. 

Given the number of issues this PR tackles, as I was developing the code, I realized that splitting it into completely independent, atomic PRs would have significantly impacted development time. Obviously, there are tradeoffs to that decision which appear in the form of not-so-easy reviews. I understand that a comprehensive review may be challenging within a reasonable timeframe. I propose we prioritize identifying any obvious "red flags" and rely on the integration tests to verify the overall behaviour.  We can continue to improve the codebase iteratively in future PRs.

**Review by robscott — COMMENTED** [review]
Thanks @gauravkghildiyal! Partial review from last week, will try to get back to this soon.

**Comment by shaneutt** [comment]
@gauravkghildiyal at this point should we close this and apply it to the new repository, since this is getting moved?

**Comment by gauravkghildiyal** [comment]
Thanks Shane, thanks Rob!

I'll archive any other open PRs and issues too, or suggest people reopen them on kubernetes-sigs/gwctl

**Pull request closed without merging**
