### PR TITLE
docs: merge 'custom' and 'implementation-specific' conformance

### LINKED ISSUE #640: Audit the code base and make sure that our usage of custom vs implementation-specific is accurate AND/OR fix the description in the guidelines.
Audit the code base and make sure that our usage of custom vs implementation-specific is accurate AND/OR fix the description in the guidelines.

References:

* https://github.com/kubernetes-sigs/gateway-api/pull/639
* https://github.com/kubernetes-sigs/gateway-api/issues/530

### PR DESCRIPTION
**Pull request by LCaparelli**
Signed-off-by: Lucas Caparelli <lucas.caparelli@gympass.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

This PR merges the concepts of `custom` and `implementation-specific` conformance into `implementation-specific` only in order to simplify the spec. All `custom` conformance mentions were replaced by `implementation-specific`.

**Which issue(s) this PR fixes**:

Fixes #640 

**Does this PR introduce a user-facing change?**:

```release-note
Changes "custom" conformance level to "implementation-specific"
```

### CODE REVIEW

**Comment by LCaparelli** [comment]
I also changed these in the GEPs, please let know if that's unwanted.

**Comment by robscott** [comment]
Thanks @LCaparelli! This looks like a good simplification to me but will defer to another maintainer to confirm since this is changing our language around conformance levels.

/ok-to-test
/lgtm

/cc @youngnick @shaneutt

**Comment by shaneutt** [comment]
let's give it a kick.

/retest

**Comment by LCaparelli** [comment]
I'll take a closer look at what the script does, had some trouble with an outdated `kubectl` on my side, might be picking up some other old dependency on my end.

**Comment by robscott** [comment]
Hey @LCaparelli, sorry for the confusion here, I think the k8s codegen requires that you're using go1.19 now.

**Comment by robscott** [comment]
Thanks @LCaparelli! This LGTM, will defer to @youngnick or @shaneutt to formally sign off on this change though.

> Adding a quick version check at the codegen script sounds reasonable @robscott? And if so, it it ok to include in this PR?

This is a great idea, do you mind filing a follow up PR for that?

**Review by shaneutt — APPROVED** [review]
Yep, I like this change :+1: 

/lgtm

**Comment by LCaparelli** [comment]
Thanks @robscott @shaneutt! Follow-up for version check: https://github.com/kubernetes-sigs/gateway-api/pull/1443

**Pull request merged**
