### PR TITLE
use squash as default merge behavior

### PR DESCRIPTION
**Pull request by hbagdi**
**What type of PR is this?**

**What this PR does / why we need it**:
This automation makes tide use squash as  the default merge method so that PR authors can make incremental commits through the review process.
**Which issue(s) this PR fixes**:

None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
I'm not sure how I feel about this. I think there are some cases where PRs are large enough in scope where multiple commits could be helpful. On the other hand, this label would likely be more frequently helpful than annoying. I'll defer to someone else to add the final LGTM on this, I don't think I have a strong enough opinion either way here.

**Comment by hbagdi** [comment]
>  I think there are some cases where PRs are large enough in scope where multiple commits could be helpful.

100%. It is less common and so I thought having this label as the default behavior might help.
I don't feel strongly either way.

**Comment by youngnick** [comment]
I think this is great, since most of the time the PR creator will need to squash down to one commit anyway.

**Comment by bowei** [comment]
Does prow and tide support squash now? We had a discussion several years ago and we had to switch to merge from squash.

**Comment by hbagdi** [comment]
> Does prow and tide support squash now? We had a discussion several years ago and we had to switch to merge from squash.

Seems so. https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md

**Pull request merged**
