### PR TITLE
Updating changelog for v0.4.1

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This updates the changelog to include v0.4.1. Approving this PR means that you approve the release of this bundle version  of the API at this commit. 

For this to merge, #909 and #964 will first have to be cherry picked back to the release-0.4 branch. When that is complete, this PR will be rebased. Finally, immediately post release, this changelog PR will have to be cherry-picked to master.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/hold

### CODE REVIEW

**Comment by robscott** [comment]
Holding off on this until we can include https://github.com/kubernetes-sigs/gateway-api/pull/956 as well.

**Comment by robscott** [comment]
@bowei @hbagdi @jpeach @youngnick This PR has been updated to include #956 now that the cherry pick has merged. PTAL. Will release v0.4.1 once this merges.

**Comment by hbagdi** [comment]
Let's roll!
/lgtm

**Pull request merged**
