### PR TITLE
fix ReferencePolicyList.Items type

### PR DESCRIPTION
**Pull request by dprotaso**
**What type of PR is this?**

**What this PR does / why we need it**:

When the ReferencePolicy type was added back the list type for that resource actually returns ReferenceGrants instead of ReferencePolicy. This isn't a huge deal but a lot of code generation around k8s types assume a pattern of `XResource` with a `XResourceList` having an `Items` type of `[]XResource`

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

```release-note
ReferencePolicyList Items is an array of ReferencePolicy again
```

### CODE REVIEW

**Comment by dprotaso** [comment]
Weird - I thought I was a member of the k8s org - does the k8s-sigs have it's own org/membership repo?

**Comment by robscott** [comment]
Thanks @dprotaso! 

/ok-to-test

**Comment by robscott** [comment]
> Weird - I thought I was a member of the k8s org - does the k8s-sigs have it's own org/membership repo?

Yep, we're under kubernetes-sigs org. Any kubernetes member can join kubernetes-sigs by making a PR like this:

https://github.com/kubernetes/org/pull/3520

**Pull request merged**
