### PR TITLE
Adding structure to site-src to match site structure

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
This updates the structure of site-src to match site structure. Unfortunately this will result in some URLs changing, notably any external links to pages like spec will no longer be valid. Although that is not ideal, I think it's better to get this out of the way earlier than later so we don't have to have an entirely flat docs structure forever.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/464

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by danehans** [comment]
Per community meeting feedback, @robscott will see if tooling exists to check internal links.

**Comment by hbagdi** [comment]
grep reveals the following misses:
```
.github/PULL_REQUEST_TEMPLATE.md:   developer guide (https://gateway-api.sigs.k8s.io/devguide/)
.github/PULL_REQUEST_TEMPLATE.md:   and our community page (https://gateway-api.sigs.k8s.io/community/).
```

```
README.md:[cm]: https://gateway-api.sigs.k8s.io/community
```

```
RELEASE.md:[the release documentation]: https://gateway-api.sigs.k8s.io/releases/#versioning
```

**Comment by robscott** [comment]
Thanks for following up on this @danehans and @hbagdi! Unfortunately it does not look like there's any great way to automate checks for broken links yet. I believe I've fixed most/all of them, including the ones Harry listed above. Let me know if I missed anything.

**Comment by hbagdi** [comment]
Okay. I went through this again briefly. There are online tools like https://www.deadlinkchecker.com/website-dead-link-checker.asp which could help a little bit after merge.

/lgtm

**Pull request merged**
