### PR TITLE
chore: remove `conformance/reports/latest` link

### PR DESCRIPTION
**Pull request by pmalek**
**What type of PR is this?**

/kind cleanup
/area conformance

**What this PR does / why we need it**:

Removes the `conformance/reports/latest`.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shaneutt** [comment]
So I was thinking about this, and all things considered: I don't think we actually need this symlink. It would be _potentially_ a convenience if we were programmatically scanning the latest, but even then we could just use semver to figure that out. So rather than have to add a release step and all that, maybe we should just remove it entirely?

**Comment by pmalek** [comment]
> So I was thinking about this, and all things considered: I don't think we actually need this symlink. It would be _potentially_ a convenience if we were programmatically scanning the latest, but even then we could just use semver to figure that out. So rather than have to add a release step and all that, maybe we should just remove it entirely?

👍 Removed

**Review by mlavacca — APPROVED** [review]
Thanks @pmalek!

/ok-to-test
/approve

**Review by shaneutt — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
