### PR TITLE
Correct the version mention in the Status

### LINKED ISSUE #1048: Change the version mention
**What happened**:
Latest supported version [status](https://github.com/kubernetes-sigs/gateway-api#status) is mentioned wrong in the [README.md](https://github.com/kubernetes-sigs/gateway-api#readme).

It doesn't match with the site.
k8s_signet

**What you expected to happen**:
We should correct the version in README.md to avoid misconceptions.

**How to reproduce it (as minimally and precisely as possible)**:
Currently, it is written:
`The latest supported version is v1alpha2 as released by the [v0.4.0 release](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.4.0) of this project.`

I think we should change it to:
`The latest supported version is v1alpha2 as released by the [v0.4.2 release](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.4.2) of this project.`

### PR DESCRIPTION
**Pull request by Anubhavdevv**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Correct the version mention in the Status in Readme

**Which issue(s) this PR fixes**:

Fixes #1048

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by verma-kunal — APPROVED** [review]
Lgtm! Thanks @Anubhavdevv

**Comment by robscott** [comment]
Thanks @Anubhavdevv!

/approve

**Comment by Anubhavdevv** [comment]
Thank You 🙌

**Pull request merged**
