### PR TITLE
Add Programmed to known gateway condition types

### PR DESCRIPTION
**Pull request by MichaelVL**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR adds `Programmed` to the documentation of known `Gateway` conditions.

**Which issue(s) this PR fixes**:
No issue identified

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Comment by arkodg** [comment]
you probably also need to update CRDs using `make generate`

**Review by shaneutt — APPROVED** [review]
Yep, seems like a fair change we didn't update this when we added the `Programmed` distinction :+1: 

Thank you!

/lgtm

**Pull request merged**
