### PR TITLE
Fix Grammar

### PR DESCRIPTION
**Pull request by mazak-ui**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by robscott** [comment]
Hey @mazak-ui, thanks for the PR! Please follow the directions above to sign the CLA.

**Comment by mazak-ui** [comment]
> Hey @mazak-ui, thanks for the PR! Please follow the directions above to sign the CLA.

Hello @robscott - My bad, wasn't sure if that applied to quick documentation edits. I've completed the DocuSign/CLA.

**Comment by robscott** [comment]
@mazak-ui not sure what happened here, asked around in [sig-contribex Slack](https://kubernetes.slack.com/archives/C1TU9EB9S/p1640809274454100). Looks like you may still need to sign/re-sign the CLA? Not sure why there's a conflict between the CLA tooling here.

**Comment by mazak-ui** [comment]
@robscott - I just resigned, let me know. Thanks!

**Comment by robscott** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
