### PR TITLE
docs: improve documentation about the reports version

### PR DESCRIPTION
**Pull request by mlavacca**
**What type of PR is this?**

/kind documentation
/area conformance

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Good to know, thanks :+1:

**Review by shaneutt — APPROVED** [review]
/approve

**Pull request merged**
