### PR TITLE
Added HTTP/2 support in conformance test roundtripper

### LINKED ISSUE #1982: Request for information/support on http2 transport enablement in conformance test
**What would you like to be added**:
Need support for http2 in conformance test specifically the "roundtripper" package

**Why this is needed**:
To overcome limitation of just using http1 in the conformance test as the upstream backend host might just support only http2
https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/utils/roundtripper/roundtripper.go#L111

**Additional Details **:
From the initial investigation, it looks like we cannot pass the custom HTTP client into the default round tripper implementation. If there is an alternate way to achieve this, I would like to be redirected there.

### PR DESCRIPTION
**Pull request by ibilalkayy**
What type of PR is this?

/kind feature
/area conformance

**What this PR does / why we need it:**

This PR adds support for HTTP/2 in the conformance test **roundtripper** package. The changes include updating the **Request** struct in **roundtripper.go** to include an HTTP2Transport field and modifying the **defaultTransport** function in **roundtripper.go** to create an HTTP/2 transport if required, using the http2.ConfigureTransport function from the **golang.org/x/net/http2** package.

These changes will enable users to set the **HTTP2Transport** field when creating a **Request** in the conformance test, allowing for HTTP/2 support. This addition helps overcome the limitation of just using HTTP/1 in the conformance test, especially when the upstream backend host might only support HTTP/2.

**Which issue(s) this PR fixes:**

Fixes #1982

**Does this PR introduce a user-facing change?:**

`Added support for HTTP/2 in the conformance test roundtripper package.
`

### CODE REVIEW

**Comment by robscott** [comment]
Agree with @sunjayBhatia here, this would be best to save until we have test(s) that need this. @ibilalkayy was there a specific test you were hoping this would enable?

**Comment by gauravkghildiyal** [comment]
Unless, I'm missing something, I believe one can already achieve the requirements of the issue. Refer comment https://github.com/kubernetes-sigs/gateway-api/issues/1982#issuecomment-1528727074

Please correct me if I misunderstood something.

**Comment by sunjayBhatia** [comment]
> Unless, I'm missing something, I believe one can already achieve the requirements of the issue. Refer comment [#1982 (comment)](https://github.com/kubernetes-sigs/gateway-api/issues/1982#issuecomment-1528727074)
> 
> Please correct me if I misunderstood something.

All the existing conformance tests use a known backend that is deployed as part of the tests (the ingress-conformance echo server) so there isn't anything in the tests I'm aware of that an HTTP/2 backend is relevant for yet (the still-draft conformance tests for gRPC route look like they will have their own gRPC echo server but will use a gRPC client)

**Review by pramodrj07 — COMMENTED** [review]
LGTM. I was thinking of passing the client. But this seems like a better solution.

**Comment by aojea** [comment]
> gRPC echo server but will use a gRPC client

just important note for e2e tests and something that is a terrible headache is that grpc uses http2 under the hood https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md, so the only way to differentiate between http2 and grpc at the transport level is by checking the "content-type" header  that should begin with "application/grpc"

**Comment by pramodrj07** [comment]
> t to save until we have test(s) that need thi

We are using conformance tests to test specific scenarios where we need http2 support. Currently we have a wrapper around the existing round tripper. But this native support will be much helpful going forward. 

@sunjayBhatia - Agree to your point on non-existence of any http2 related conformance test at the moment. Going forward do you see any support for http2 support in the near future?

**Comment by sunjayBhatia** [comment]
> @sunjayBhatia - Agree to your point on non-existence of any http2 related conformance test at the moment. Going forward do you see any support for http2 support in the near future?

The outcome of this GEP should lead to some conformance tests being developed: https://github.com/kubernetes-sigs/gateway-api/pull/1979

**Comment by shaneutt** [comment]
As this PR hasn't received an update in some time, and needs some conflict resolution I'm going to mark this as "draft" for the time being as this helps us to better organize our reviews. Please let us know if you're blocked!

**Pull request closed without merging**
