### PR TITLE
doc: gwctl - improve readme, add Makefile

### PR DESCRIPTION
**Pull request by pottekkat**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Adds a basic Makefile to build the gwctl binary and improves the documentation in the readme.

**Which issue(s) this PR fixes**: none

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pottekkat** [comment]
Hi, I have a question. gwctl should be in a separate repository similar to https://github.com/kubernetes-sigs/ingress2gateway, right? Is there any particular reason why it is kept here? Having a separate repository could make it easier to manage.

I can help improve gwctl, as mentioned by @robscott in this comment: https://github.com/kubernetes-sigs/gateway-api/pull/2428#issuecomment-1751530167.

But I don't see any open issues. Do you think I should create them? Some of the problems I think we need to fix initially are:

1. Failing gracefully: Currently, gwctl throws a lot of errors when an expected resource or something else is missing. We can add checks to prevent this and fail gracefully while showing better messages to the user.
2. Move subcommands to proper packages: The way the code is organized can be a bit confusing. Refactoring it to look like other Go/Cobra CLI projects would be better.
3. Add tests.
4. Set up a workflow to publish binaries instead of installing them from the source.
5. Change the CLI name to kubectl-gw so that it is a kubectl plugin.

I think these are reasonable first steps, and after this, we can proceed as mentioned in [the comment](https://github.com/kubernetes-sigs/gateway-api/pull/2428#issuecomment-1751530167) by sketching out a desired UX to be a drop-in replacement for `kubectl get` can be achieved.

Let me know what you think and I can fix these!

**Comment by pottekkat** [comment]
Another thing here is that if we are running `go mod vendor`,  shouldn't those files under the vendor folder be committed? But I don't think we need it and we can remove the command from the build process.

**Comment by robscott** [comment]
Thanks @pottekkat!

/assign @gauravkghildiyal

**Comment by gauravkghildiyal** [comment]
Thanks @pottekkat! This LGTM.

/lgtm

Yes I have an upcoming PR (should be out this week) to discuss and document the next steps of gwctl, which will be followed by the creation of the relevant issues. This should help facilitate contributions towards a common goal from everyone community :)

**Comment by robscott** [comment]
Thanks @pottekkat!

/approve

**Comment by pottekkat** [comment]
@gauravkghildiyal That sounds great! I would like to get involved. I was also working on a PR to organize the code better and fail gracefully with better error messages. I can also open that PR.

**Comment by gauravkghildiyal** [comment]
@pottekkat 

That's great! I can only hope you don't run into issues with the changes from https://github.com/kubernetes-sigs/gateway-api/pull/2708 I'm trying to get this in sooner so it unblocks other development. Otherwise someone will have to deal with lots of merge conflicts :)

**Comment by gauravkghildiyal** [comment]
Hmmm I don't think the `pull-gateway-api-verify` is supposed to take so long.

/retest

**Pull request merged**
