### PR TITLE
Removing v1alpha1 generated code and validation

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This removes the generated code and validation for v1alpha1. Since v1alpha1 was essentially frozen with the v0.3.0 release, it does not make sense to maintain the code generation and validation beyond that point. For reference, the [Kubernetes deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api) states that we need to maintain deprecated alpha API versions for _0_ releases.

Note that this intentionally leaves all of the following in place as they are required for our documentation:

- API types
- Examples
- Docs

**Does this PR introduce a user-facing change?**:
```release-note
The v1alpha1 API version has been removed. 
```

/hold for consensus

### CODE REVIEW

**Comment by robscott** [comment]
For more context on this PR, I'm getting back into code generation to support experimental fields as part of our updated versioning strategy. As I was updating code generation, it didn't make sense to workaround v1alpha1. Although it's still helpful to have the docs in place (maintained by this PR), the codegen is effectively wasted effort at this point in my opinion.

**Comment by youngnick** [comment]
I agree that getting rid of this is probably for the best.

/lgtm
/hold for further review.

**Pull request merged**
