### PR TITLE
Adding changelog for v1.1.0

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This adds the changelog for v1.1.0 and corresponding version bumps where needed. Approving this PR means that you're approving the release of Gateway API v1.1.0.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/hold for consensus
/assign @shaneutt @youngnick

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM

**Comment by howardjohn** [comment]
(Intentionally did not lgtm since this probably should have >1 approver)

**Review by mlavacca — APPROVED** [review]

**Pull request merged**
