### PR TITLE
conformance: Add test for ensuring route match order is respected

### PR DESCRIPTION
**Pull request by sunjayBhatia**
**What type of PR is this?**

/kind cleanup
/kind documentation

**What this PR does / why we need it**:

Adds a conformance test for a currently ambiguous header matching case.

The request with headers `version: two` and `color: blue` matches both

```
  # Matches "version: two"
  - matches:
    - headers:
      - name: version
        value: two
    backendRefs:
    - name: infra-backend-v2
      port: 8080
```
and
```
  # Matches "color: blue" OR "color: green"
  - matches:
    - headers:
      - name: color
        value: blue
    - headers:
      - name: color
        value: green
    backendRefs:
    - name: infra-backend-v1
      port: 8080
```

with Contour, since we generate matches for OR matches as separate routes which are then sorted (by number of header matches and then alphanumerically on header), the second route rule above would have precedence

However, according to this language: https://github.com/kubernetes-sigs/gateway-api/blob/a3f769e5c690546140b6b9f0db5aea4d766b8f68/apis/v1beta1/httproute_types.go#L161-L163

the *first* route should be given precedence.

~~As far as I can tell there isn't anything in the `HTTPRouteMatch` documentation that covers this.~~

~~There is a [note](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule) about preference going to the route match with `the largest number of ... Header matches`, however does that does not seem to apply in the OR case here and maybe needs to be clarified. If instead of including the header `color` in our request/match we used something that sorted alphanumerically after `version`, Contour at least would route to `infra-backend-v2` (the first match listed above)~~

~~Seems like we could add to the documentation for route match conflict resolution section something about what to do in this case?~~

**Which issue(s) this PR fixes**:

Updates: #1102

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by shaneutt — COMMENTED** [review]
When looking just at the diff, it's not clear how this differentiates from the test case right above it. Am I missing something?

**Comment by sunjayBhatia** [comment]
> When looking just at the diff, it's not clear how this differentiates from the test case right above it. Am I missing something?

the previous case is distinct as it should exactly match this rule:

```
  # Matches "version: two" AND "color: orange"
  - matches:
    - headers:
      - name: version
        value: two
      - name: color
        value: orange
    backendRefs:
    - name: infra-backend-v1
      port: 8080
```

**Review by shaneutt — APPROVED** [review]
Ah! It was too early in the morning :coffee:++

I was looking at the wrong thing and was getting confused. Looks good.

/lgtm

**Comment by sunjayBhatia** [comment]
> Ah! It was too early in the morning ☕++
> 
> I was looking at the wrong thing and was getting confused. Looks good.
> 
> /lgtm

Also generally have a question that goes with this test

```
There is a note about preference going to the route match with the largest number of ... Header matches, however does that does not seem to apply in the OR case here and maybe needs to be clarified. If instead of including the header color in our request/match we used something that sorted alphanumerically after version, Contour at least would route to infra-backend-v2 (the first match listed above)

Seems like we could add to the documentation for route match conflict resolution section something about what to do in this case?
```

The test case here isn't explicitly covered by any of the documentation in the spec as far as I can tell

**Comment by sunjayBhatia** [comment]
There are a few ambiguities like this that conformance tests can show easily but may be missed in the godoc/field descriptions in the API. In this case I think the test change should be accompanied by an addition to the language in the route matching API description. Is this the right process to do so in the same change?

**Comment by shaneutt** [comment]
> There are a few ambiguities like this that conformance tests can show easily but may be missed in the godoc/field descriptions in the API. In this case I think the test change should be accompanied by an addition to the language in the route matching API description. Is this the right process to do so in the same change?

For that we would probably want a couple of reviewers whereas for this it's just adding a functional test case, so I feel it's reasonable to merge this and then add the language change as a separate PR. It's your choice however.

**Comment by sunjayBhatia** [comment]
Actually re-reading the spec

```
	// If ties still exist within the Route that has been given precedence,
	// matching precedence MUST be granted to the first matching rule meeting
	// the above criteria.
```

so actually, this test should route to the v1 backend since the match for `version: two` comes before the other possible match in the list of routes

**Comment by sunjayBhatia** [comment]
hm, didnt mean to remove reviewers, but re-requesting a review did so

**Review by shaneutt — APPROVED** [review]
I think it looks good, but I'll just ask @youngnick to do a double tap. :+1:

**Review by youngnick — COMMENTED** [review]
Thanks for picking this up, @sunjayBhatia!

/lgtm

**Comment by skriss** [comment]
@sunjayBhatia reading the current spec literally, I would think this request should go to `infra-backend-v1`. Per https://github.com/kubernetes-sigs/gateway-api/blob/a3f769e5c690546140b6b9f0db5aea4d766b8f68/apis/v1beta1/httproute_types.go#L143-L152, we should prioritize the **Rule** with the greatest number of header matches, which in this case is:

```
 # Matches "color: blue" OR "color: green"
  - matches:
    - headers:
      - name: color
        value: blue
    - headers:
      - name: color
        value: green
    backendRefs:
    - name: infra-backend-v1
      port: 8080
```

Since this is a single Rule that has 2 header matches (even though each individual Match within the role only has one each).

**Review by shaneutt — APPROVED** [review]
/lgtm

**Comment by sunjayBhatia** [comment]
@shaneutt re: https://github.com/kubernetes-sigs/gateway-api/pull/1370#issuecomment-1238472815

looks like we may not have agreement on how this should work and the exact language involved

**Comment by sunjayBhatia** [comment]
See https://github.com/kubernetes-sigs/gateway-api/issues/1381

**Comment by shaneutt** [comment]
> looks like we may not have agreement on how this should work and the exact language involved

Yep my apologies. Let's follow up in #1381 as you've proposed.

**Pull request merged**
