### PR TITLE
fix: typo: indent

### PR DESCRIPTION
**Pull request by dspo**
fix: typo: indent

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

fix typo in document.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]
/ok-to-test

/lgtm

**Comment by Xunzhuo** [comment]
Plz sign the CLA first @dspo

**Review by shaneutt — APPROVED** [review]
Thanks! :+1: 

/lgtm

**Pull request merged**
