### PR TITLE
Add GEP-2722 covering the goals, motivations and UX of gwctl.

### PR DESCRIPTION
**Pull request by gauravkghildiyal**
**What type of PR is this?**
/kind gep

**What this PR does / why we need it**:
This PR adds a memorandum GEP for `gwctl` (https://github.com/kubernetes-sigs/gateway-api/issues/2722)

Preview: https://deploy-preview-2723--kubernetes-sigs-gateway-api.netlify.app/geps/gep-2722/

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gauravkghildiyal** [comment]
Added some information about expected distribution processes.

@youngnick, @robscott -- Please take a look as per convenience. I'm assuming we're aligned on the overall desire to have something like `gwctl` so I will start tasking this out (for others to be able to contribute) and executing in parallel while we discuss the finer details here.

Let me know if you have any concerns.

**Comment by gauravkghildiyal** [comment]
Preview at https://deploy-preview-2723--kubernetes-sigs-gateway-api.netlify.app/geps/gep-2722/

(Finally got the markdown behaviour right -- seems like [nested lists require 4 spaces of indent](https://github.com/Python-Markdown/markdown/issues/3).)

**Review by shaneutt — APPROVED** [review]
Looks good, /cc @youngnick

**Comment by youngnick** [comment]
Sorry about the delay @gauravkghildiyal, nice work.

/lgtm

**Review by shaneutt — APPROVED** [review]
/approve

**Comment by youngnick** [comment]
Ah, @gauravkghildiyal, we also need to have the GEP added into `mkdocs.yml` in the root of the repo so that it will show up in the GEP list.

**Comment by gauravkghildiyal** [comment]
@youngnick Ahh thanks. Yes I was wondering why it didn't show up there.

**Pull request merged**
