### PR TITLE
chore: updates for default branch rename

### LINKED ISSUE #1195: Rename "master" default branch to "main"
**What would you like to be added**:

It seems like we're eventually going to want to rename `master` to `main`. This is a proposal that we do that before `v0.5.0` when we start releasing BETA APIs, because the longer we wait the more trouble the change will be.

**Checklist From [Upstream Rename Documentation](https://www.kubernetes.dev/resources/rename/)**:

- [x] create an issue in your repo to track the branch rename. You can paste this checklist in the issue body.
- [x] If you are not a root approver for the repo, assign a root approver for approval.
- [x] Once the issue has been approved, send a notice to your SIG’s mailing list about the potential branch rename.
- [x] If the repo has netlify configured for it, ask a member of the GitHub Management Team to rename the master branch to main in the netlify site config. It can’t be controlled through the netlify config in the repo.
- [ ] https://github.com/kubernetes/test-infra/pull/26536
- [ ] https://github.com/kubernetes-sigs/gateway-api/pull/1196

### PR DESCRIPTION
**Pull request by shaneutt**
**What type of PR is this?**

/kind cleanup
/kind documentation

**What this PR does / why we need it**:

This updates references to the default branch to the up-to-date name.

**Which issue(s) this PR fixes**:

Fixes #1195

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shaneutt** [comment]
On hold until all of the other work for https://github.com/kubernetes-sigs/gateway-api/issues/1195 is resolved.

/hold

**Comment by youngnick** [comment]
The changes lgtm, I'll approve, then we can do a final lgtm when we're ready to release the hold.

/approve

**Comment by shaneutt** [comment]
Our repository and our netlify have been updated to the new default branch, this is no longer on hold.

/unhold

**Comment by robscott** [comment]
Thanks @shaneutt!

/lgtm

**Pull request merged**
