### PR TITLE
Fix trivial wording issues.

### PR DESCRIPTION
**Pull request by briantkennedy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some wording issues my linter is complaining about.

**Which issue(s) this PR fixes**:
N/A, very tiny change.

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]
/lgtm

**Comment by shaneutt** [comment]
It looks like something is broken with GRPCRoute:

```console
GRPCRoute in version "v1alpha2" cannot be handled as a GRPCRoute
```

I'll try and take a look at this soon when I have some cycles.

**Comment by robscott** [comment]
Thanks @briantkennedy! It looks like you need to run `make generate` to get tests to pass, otherwise LGTM.

**Comment by shaneutt** [comment]
@briantkennedy since we hadn't heard back from you in a while, I added the one-line missing from the `make generate` so we could go ahead and get this merged. Thank you for your contribution!

**Review by shaneutt — APPROVED** [review]
/lgtm

**Pull request merged**
