### PR TITLE
Mesh Conformance IPv6 fix

### PR DESCRIPTION
**Pull request by keithmattix**
This builds on #2024 by applying it to the mesh conformance host logic as well

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by keithmattix** [comment]
@shaneutt @michaelbeaumont @kflynn Any issues with this PR? Would love to get this merged in for 0.8.0

**Review by michaelbeaumont — APPROVED** [review]
LGTM

**Comment by robscott** [comment]
Thanks @keithmattix!

/lgtm

**Pull request merged**
